#!/usr/bin/env node
// academy/tools/v1_2_review.js - data section of the v1.2 review.
// Reads the baseline, v1.1 and v1.2 reports and writes tables + verbatim
// responses. Capability violations and routing failures are reported
// SEPARATELY from the four dimensions, as requested.
//   node academy/tools/v1_2_review.js > academy/reports/sample-v1_2-review.data.md
const path = require('path');
const REP = path.join(__dirname, '..', 'reports');
const R = (f) => require(path.join(REP, f));
const { guard } = require('../lib/action_guard');
const idx = (r) => Object.fromEntries(r.results.map((c) => [c.case_id, c]));

const BASE = { ...idx(R('sample-baseline.json')), ...idx(R('sample-v1_1-regression-baseline.json')) };
const V11 = idx(R('sample-v1_1-candidate.json'));
const V12 = idx(R('sample-v1_2-candidate.json'));
const TEAM = idx(R('sample-v1_2-team.json'));
const DIMS = ['expertise', 'judgment', 'relationship', 'execution'];
const J = ['anthropic:claude-sonnet-5', 'openai:gpt-5.6-terra'];
const s = (v) => ({ pass: 'P', fail: 'F', needs_review: 'NR' }[v] || '-');
const wc = (t) => String(t || '').split(/\s+/).filter(Boolean).length;
const runsOf = (rec, d) => (rec ? rec.runs.filter((r) => r.dimensions).map((r) => s(r.dimensions[d].verdict)).join('/') : '-');
const quote = (t) => String(t || '').split('\n').map((l) => `> ${l}`).join('\n');
const out = [];
const P = (...x) => out.push(...x);

function tally(set, ids) {
  const t = Object.fromEntries(DIMS.map((d) => [d, { pass: 0, needs_review: 0, fail: 0 }]));
  let splits = 0, runs = 0, conf = 0, flags = 0, words = 0, inconsistent = 0;
  for (const id of ids) {
    const c = set[id]; if (!c) continue;
    inconsistent += Object.values(c.consistency || {}).filter((v) => !v.consistent).length;
    for (const r of c.runs.filter((x) => x.dimensions)) {
      runs++; words += wc(r.message);
      for (const d of DIMS) {
        const x = r.dimensions[d]; t[d][x.verdict]++;
        const bj = x.by_judge || {};
        if (bj[J[0]] && bj[J[1]] && bj[J[0]].verdict !== bj[J[1]].verdict) splits++;
      }
      for (const f of r.critical_failures || []) { flags++; if (f.status === 'confirmed') conf++; }
    }
  }
  return { t, splits, runs, conf, flags, words: runs ? Math.round(words / runs) : 0, inconsistent, cells: ids.filter((i) => set[i]).length * 4 };
}

// Apply the v1.2 guard, as an auditor, to FINAL messages of any version, so the
// five v1.1 regressions are counted the same way everywhere.
const AUDIT = { INVENTED_ORG_ROLE: 'invented org role', AUTHORITY: 'unauthorized bind/sign/approve', CAPABILITY: 'capability (phone, physical, posting, payment)', UNSOURCED_LEGAL: 'unsourced legal claim', TYPICAL_AS_RULE: 'typical norm as rule' };
function ctxOf(c) { return [...(c.available_context || []).map((x) => `${x.text} ${x.source}`), ...(c.conversation_history || []).map((h) => h.text)].join('\n'); }
const CASES = {};
for (const f of ['interaction.json', 'technical.json', 'regression_v1_1.json']) { const raw = require(path.join(__dirname, '..', 'cases', f)); for (const c of (raw.cases || raw)) CASES[c.case_id] = c; }
function audit(set, ids) {
  const counts = Object.fromEntries(Object.keys(AUDIT).map((k) => [k, 0])); const hits = [];
  for (const id of ids) {
    const c = set[id]; if (!c) continue;
    for (const r of c.runs.filter((x) => x.message)) {
      for (const v of guard({ message: r.message, contextText: ctxOf(CASES[id] || {}), actionLog: (CASES[id] || {}).action_log || [], agent: 'amanda', commitments: r.commitments || [] })) {
        if (counts[v.rule] === undefined) continue;
        counts[v.rule]++; hits.push(`${id} r${r.run} ${v.rule}: "${v.sentence}"`);
      }
    }
  }
  return { counts, hits };
}

const amandaIds = Object.keys(V12);
const teamIds = Object.keys(TEAM);

// ---- 1. team routing ------------------------------------------------------------
P('# v1.2 data (generated by academy/tools/v1_2_review.js)', '');
P('## A. Team-routing cases (16 cases x 2 runs)', '');
P('| Case | Agent | Expected owner / mode | expertise | judgment | relationship | execution | routing failures | handoff problems | capability first -> final |', '|---|---|---|---|---|---|---|---|---|---|');
for (const id of teamIds) {
  const c = TEAM[id]; const rs = c.runs.filter((r) => r.dimensions);
  const exp = rs[0] ? '' : '';
  const caseDef = require(path.join(__dirname, '..', 'team', 'cases', 'team_routing.json')).cases.find((x) => x.case_id === id);
  const rt = rs.map((r) => (r.routing.violations.map((v) => v.code.replace('RT_', '')).join(', ') || 'ok')).join(' / ');
  const ho = rs.map((r) => (caseDef.expected_handoff ? (r.routing.handoff_problems.map((v) => v.code.replace('HO_', '')).join(', ') || 'ok') : 'n/a')).join(' / ');
  const cap = rs.map((r) => `${r.guard.capability_first.length}->${r.guard.capability_final.length}`).join(' / ');
  P(`| ${id} ${c.title} | ${c.agent} | ${caseDef.expected_routing.owner} / ${caseDef.expected_routing.mode} | ${DIMS.map((d) => runsOf(c, d)).join(' | ')} | ${rt} | ${ho} | ${cap} |${exp}`);
}
const tt = tally(TEAM, teamIds);
P('', `Totals (${tt.runs} replies): ${DIMS.map((d) => `${d} ${tt.t[d].pass} pass / ${tt.t[d].needs_review} NR / ${tt.t[d].fail} fail`).join('; ')}. Confirmed criticals ${tt.conf} of ${tt.flags} flags. Judge splits ${tt.splits}. Cross-run inconsistent ${tt.inconsistent} of ${tt.cells}. Mean ${tt.words} words.`, '');

P('### Routing failures (reported separately)', '');
let nRoute = 0;
for (const id of teamIds) for (const r of TEAM[id].runs.filter((x) => x.routing)) {
  for (const v of r.routing.violations) { nRoute++; P(`- ${id} r${r.run} **${v.code}**: ${v.detail}`); }
  for (const v of r.routing.handoff_problems) { nRoute++; P(`- ${id} r${r.run} **${v.code}**: ${v.detail}`); }
  for (const f of (r.critical_failures || []).filter((x) => ['CF_WRONG_OWNER', 'CF_HANDOFF_CONTEXT_LOST', 'CF_TEAMMATE_WORK_DENIED'].includes(x.code))) { nRoute++; P(`- ${id} r${r.run} **${f.code}** (judges: ${f.status}): ${(f.flags[0] || {}).why || ''}`); }
}
if (!nRoute) P('- none');
P('');

// ---- 2. capability violations -----------------------------------------------------
P('## B. Capability violations (reported separately; both suites)', '');
let nCap = 0;
for (const [label, set, ids] of [['team', TEAM, teamIds], ['amanda v1.2', V12, amandaIds]]) {
  for (const id of ids) for (const r of set[id].runs.filter((x) => x.guard)) {
    for (const v of r.guard.capability_first) { nCap++; P(`- [${label}] ${id} r${r.run} first draft, **${v.capability}** (${v.tense || 'commitment'}): "${v.sentence}" -> ${r.guard.capability_final.some((f) => f.sentence === v.sentence) ? 'STILL IN FINAL' : 'removed in revision'}`); }
    for (const v of r.guard.capability_final.filter((f) => !r.guard.capability_first.some((x) => x.sentence === f.sentence))) { nCap++; P(`- [${label}] ${id} r${r.run} introduced by revision, **${v.capability}**: "${v.sentence}"`); }
    for (const f of (r.critical_failures || []).filter((x) => x.code === 'CF_CAPABILITY_CLAIM' && !(x.flags || []).every((g) => g.judge === 'action_guard'))) { nCap++; P(`- [${label}] ${id} r${r.run} judge-flagged CF_CAPABILITY_CLAIM (${f.status}): ${(f.flags[0] || {}).evidence || ''}`); }
  }
}
if (!nCap) P('- none');
P('');

// ---- 3. the five v1.1 regressions, audited identically ------------------------------
P('## C. The v1.1 regressions, audited with the same v1.2 guard on final messages (16 Amanda cases x 2)', '');
const aB = audit(BASE, amandaIds), a11 = audit(V11, amandaIds), a12 = audit(V12, amandaIds);
P('| Pattern | baseline | v1.1 | v1.2 |', '|---|---|---|---|');
for (const [k, lab] of Object.entries(AUDIT)) P(`| ${lab} | ${aB.counts[k]} | ${a11.counts[k]} | ${a12.counts[k]} |`);
P('', 'v1.2 hits:', ...(a12.hits.length ? a12.hits.map((h) => `- ${h}`) : ['- none']), '');

// ---- 4. v1.1 cases: baseline -> v1.1 -> v1.2 ----------------------------------------
P('## D. Existing cases: baseline -> v1.1 -> v1.2 (run 1/run 2)', '');
P('| Case | expertise | judgment | relationship | execution |', '|---|---|---|---|---|');
for (const id of amandaIds) P(`| ${id} ${V12[id].title} | ${DIMS.map((d) => `${runsOf(BASE[id], d)} -> ${runsOf(V11[id], d)} -> ${runsOf(V12[id], d)}`).join(' | ')} |`);
const tB = tally(BASE, amandaIds), t11 = tally(V11, amandaIds), t12 = tally(V12, amandaIds);
P('', '| Measure | baseline | v1.1 | v1.2 |', '|---|---|---|---|');
for (const d of DIMS) P(`| ${d} pass (of ${t12.runs}) | ${tB.t[d].pass} | ${t11.t[d].pass} | ${t12.t[d].pass} |`);
for (const d of DIMS) P(`| ${d} fail | ${tB.t[d].fail} | ${t11.t[d].fail} | ${t12.t[d].fail} |`);
P(`| confirmed criticals | ${tB.conf} | ${t11.conf} | ${t12.conf} |`, `| all critical flags | ${tB.flags} | ${t11.flags} | ${t12.flags} |`, `| judge split verdicts | ${tB.splits} | ${t11.splits} | ${t12.splits} |`, `| cross-run inconsistent (of ${t12.cells}) | ${tB.inconsistent} | ${t11.inconsistent} | ${t12.inconsistent} |`, `| mean words | ${tB.words} | ${t11.words} | ${t12.words} |`, '');

// ---- 5. guard revisions: first draft vs sent ------------------------------------------
P('## E. Guard revisions (first draft vs sent), both suites', '');
for (const [label, set, ids] of [['team', TEAM, teamIds], ['amanda v1.2', V12, amandaIds]]) {
  for (const id of ids) for (const r of set[id].runs.filter((x) => x.guard && x.guard.revised)) {
    P(`### [${label}] ${id} run ${r.run}`, '', `Caught: ${r.guard.first_violations.map((v) => `${v.rule} ("${v.sentence}")`).join('; ')}`, '', '**First draft:**', '', quote(r.guard.first_draft), '', '**Sent:**', '', quote(r.message), '', `Remaining after revision: ${r.guard.final_violations.map((v) => v.rule).join(', ') || 'none'}`, '');
  }
}

// ---- 6. raw responses ---------------------------------------------------------------
P('## F. Raw responses, verbatim', '');
P('### Team-routing cases', '');
for (const id of teamIds) {
  P(`#### ${id}: ${TEAM[id].title} (${TEAM[id].agent} -> ${TEAM[id].audience})`, '');
  for (const r of TEAM[id].runs.filter((x) => x.message)) {
    P(`**Run ${r.run}** · ${wc(r.message)} words · ${DIMS.map((d) => `${d} ${s(r.dimensions[d].verdict)}`).join(', ')} · critical: ${(r.critical_failures || []).map((f) => `${f.code} (${f.status})`).join(', ') || 'none'} · prompt: ${r.guard.prompt_source}`, '', quote(r.message), '');
    if (r.handoff) P(`Handoff package: \`${JSON.stringify(r.handoff)}\``, '');
    if ((r.commitments || []).length) P(`Commitments recorded: \`${JSON.stringify(r.commitments)}\``, '');
  }
}
P('### Existing cases under v1.2 (v1.1 response shown for comparison)', '');
for (const id of amandaIds) {
  P(`#### ${id}: ${V12[id].title}`, '');
  for (const r of V12[id].runs.filter((x) => x.message)) {
    const old = (V11[id].runs.find((x) => x.run === r.run) || {}).message;
    P(`**v1.1 run ${r.run}** (${wc(old)} words)`, '', quote(old), '', `**v1.2 run ${r.run}** · ${wc(r.message)} words · ${DIMS.map((d) => `${d} ${s(r.dimensions[d].verdict)}`).join(', ')} · critical: ${(r.critical_failures || []).map((f) => `${f.code} (${f.status})`).join(', ') || 'none'}`, '', quote(r.message), '');
    if ((r.commitments || []).length) P(`Commitments recorded: \`${JSON.stringify(r.commitments)}\``, '');
  }
}
process.stdout.write(out.join('\n') + '\n');
