#!/usr/bin/env node
// academy/tools/v1_3_review.js - data section of the v1.3 review, organized by
// the categories Ed asked for (2026-09-26), each reported separately and
// compared with v1.2:
//   wrong owner | missing handoff | unnecessary Ed | missed Ed | capability |
//   unsupported legal/governance | relationship | consistency | judges
//   node academy/tools/v1_3_review.js > academy/reports/sample-v1_3-review.data.md
const path = require('path');
const REP = path.join(__dirname, '..', 'reports');
const R = (f) => require(path.join(REP, f));
const { guard } = require('../lib/action_guard');
const { bodiesFor } = require('../team/governance');
const idx = (r) => Object.fromEntries(r.results.map((c) => [c.case_id, c]));

const T12 = idx(R('sample-v1_2-team.json')), T13 = idx(R('sample-v1_3-team.json'));
const A12 = idx(R('sample-v1_2-candidate.json')), A13 = idx(R('sample-v1_3-candidate.json'));
const TEAMCASES = Object.fromEntries(require('../team/cases/team_routing.json').cases.map((c) => [c.case_id, c]));
const AMCASES = {};
for (const f of ['interaction.json', 'technical.json', 'regression_v1_1.json']) { const raw = require(path.join(__dirname, '..', 'cases', f)); for (const c of (raw.cases || raw)) AMCASES[c.case_id] = c; }
const DIMS = ['expertise', 'judgment', 'relationship', 'execution'];
const J = ['anthropic:claude-sonnet-5', 'openai:gpt-5.6-terra'];
const s = (v) => ({ pass: 'P', fail: 'F', needs_review: 'NR' }[v] || '-');
const wc = (t) => String(t || '').split(/\s+/).filter(Boolean).length;
const quote = (t) => String(t || '').split('\n').map((l) => `> ${l}`).join('\n');
const runsOf = (rec, d) => (rec ? rec.runs.filter((r) => r.dimensions).map((r) => s(r.dimensions[d].verdict)).join('/') : '-');
const out = []; const P = (...x) => out.push(...x);
const teamIds = Object.keys(T13); const amIds = Object.keys(A13);
const runsIn = (set, ids) => ids.flatMap((id) => (set[id] ? set[id].runs.filter((r) => r.dimensions).map((r) => ({ id, r })) : []));
const confirmed = (r, codes) => (r.critical_failures || []).filter((f) => codes.includes(f.code) && f.status === 'confirmed');

function ctxFor(id) {
  const c = TEAMCASES[id] || AMCASES[id] || {};
  return { c, text: [...(c.available_context || []).map((x) => `${x.text} ${x.source}`), ...(c.conversation_history || []).map((h) => h.text), ...(c.shared_work_context || []).map((w) => `${w.what} ${w.at} ${w.status}`)].join('\n') };
}
// Same, current guard applied to every SENT message (comparable across versions).
function audit(set, ids, rules) {
  const hits = [];
  for (const { id, r } of runsIn(set, ids)) {
    const { c, text } = ctxFor(id);
    for (const v of guard({ message: r.message, contextText: text, actionLog: c.action_log || [], agent: c.agent || 'amanda', commitments: r.commitments || [], governanceBodies: bodiesFor(c.community_context || {}) })) if (rules.includes(v.rule)) hits.push({ id, run: r.run, rule: v.rule, sentence: v.sentence });
  }
  return hits;
}

P('# v1.3 data (generated by academy/tools/v1_3_review.js)', '');

// ---- per-case overview -------------------------------------------------------
P('## Team-routing cases: ownership decided before drafting', '');
P('| Case | Agent | Classified owner (v1.3) | Expected | Released? r1/r2 | expertise | judgment | relationship | execution |', '|---|---|---|---|---|---|---|---|---|');
for (const id of teamIds) {
  const rs = T13[id].runs.filter((r) => r.dimensions);
  const o = rs[0] && rs[0].guard && rs[0].guard.owner;
  const exp = TEAMCASES[id].expected_routing;
  P(`| ${id} ${T13[id].title} | ${T13[id].agent} | ${o ? `${o.owner_class} / ${o.owner}${o.handoff_required ? ' (handoff)' : ''}` : '-'} | ${exp.owner} / ${exp.mode} | ${rs.map((r) => r.guard.release.status).join(' / ')} | ${DIMS.map((d) => `${runsOf(T12[id], d)} -> ${runsOf(T13[id], d)}`).join(' | ')} |`);
}
P('', 'Dimension cells: v1.2 -> v1.3, run 1/run 2.', '');

// ---- 1. wrong owner ------------------------------------------------------------
P('## 1. Wrong owner', '');
let clsWrong = 0;
for (const id of teamIds) {
  const o = T13[id].runs[0].guard.owner; const exp = TEAMCASES[id].expected_routing;
  const expOwner = exp.owner === 'self' ? TEAMCASES[id].agent : exp.owner;
  // ask_expertise: the agent keeps the work and consults the expected owner
  const ok = o.owner === expOwner || (exp.owner === 'self' && o.owner_class === 'board') || (exp.mode === 'ask_expertise' && (o.consult || []).includes(expOwner));
  if (!ok) { clsWrong++; P(`- classifier: ${id} classified ${o.owner_class}/${o.owner}, expected ${exp.owner}`); }
}
P(`- Classifier: ${teamIds.length - clsWrong} of ${teamIds.length} team cases classified to the expected owner.`, '');
const wrongPkg = (set) => runsIn(set, teamIds).filter(({ id, r }) => r.handoff && TEAMCASES[id].expected_handoff && String(r.handoff.to || '').toLowerCase() !== TEAMCASES[id].expected_handoff.to);
const wrongJ = (set, ids) => runsIn(set, ids).filter(({ r }) => confirmed(r, ['CF_WRONG_OWNER']).length);
P('| Measure | v1.2 | v1.3 |', '|---|---|---|');
P(`| handoff package addressed to the wrong owner | ${wrongPkg(T12).length} | ${wrongPkg(T13).length} |`);
P(`| judges confirmed CF_WRONG_OWNER (team) | ${wrongJ(T12, teamIds).length} | ${wrongJ(T13, teamIds).length} |`);
P(`| judges confirmed CF_WRONG_OWNER (existing cases) | ${wrongJ(A12, amIds).length} | ${wrongJ(A13, amIds).length} |`, '');
for (const { id, r } of wrongJ(T13, teamIds)) P(`- v1.3 ${id} r${r.run}: ${(confirmed(r, ['CF_WRONG_OWNER'])[0].flags[0] || {}).why || ''}`);
P('');

// ---- 2. missing handoff ------------------------------------------------------------
P('## 2. Missing handoff', '');
const needs = (set) => runsIn(set, teamIds).filter(({ id }) => TEAMCASES[id].expected_handoff);
const missing = (set) => needs(set).filter(({ r }) => !r.handoff);
const held = runsIn(T13, teamIds).concat(runsIn(A13, amIds)).filter(({ r }) => r.guard && r.guard.release && r.guard.release.status === 'held');
const gated = runsIn(T13, teamIds).concat(runsIn(A13, amIds)).filter(({ r }) => r.guard && (r.guard.gate_first || []).length);
P('| Measure | v1.2 | v1.3 |', '|---|---|---|');
P(`| replies that should hand off (team) | ${needs(T12).length} | ${needs(T13).length} |`);
P(`| ...with no package at all | ${missing(T12).length} | ${missing(T13).length} |`);
P(`| first drafts the release gate caught (v1.3) | n/a | ${gated.length} |`);
P(`| replies HELD by the gate after revision (v1.3, never sent) | n/a | ${held.length} |`);
P(`| packages that lost required context (HO_CONTEXT_LOST) | ${runsIn(T12, teamIds).filter(({ r }) => (r.routing.handoff_problems || []).some((p) => p.code === 'HO_CONTEXT_LOST')).length} | ${runsIn(T13, teamIds).filter(({ r }) => (r.routing.handoff_problems || []).some((p) => p.code === 'HO_CONTEXT_LOST')).length} |`, '');
for (const { id, r } of gated) P(`- gate caught ${id} r${r.run}: ${r.guard.gate_first.map((p) => p.detail).join('; ')} -> ${r.guard.release.status}`);
for (const { id, r } of runsIn(T13, teamIds)) for (const p of (r.routing.handoff_problems || [])) P(`- v1.3 ${id} r${r.run} ${p.code}: ${p.detail}`);
P('');

// ---- 3 + 4. Ed ------------------------------------------------------------------
P('## 3. Unnecessary Ed escalation', '');
const unEd = (set) => runsIn(set, teamIds).filter(({ r }) => (r.routing.violations || []).some((v) => v.code === 'RT_UNNEEDED_ED'));
P(`v1.2: ${unEd(T12).length} | v1.3: ${unEd(T13).length}`, ...unEd(T13).map(({ id, r }) => `- ${id} r${r.run}`), '');
P('## 4. Missed Ed escalation', '');
const edCases = teamIds.filter((id) => TEAMCASES[id].expected_routing.ed_required);
const missEd = runsIn(T13, teamIds).filter(({ r }) => (r.routing.violations || []).some((v) => v.code === 'RT_MISSED_ED'));
const missEd12 = runsIn(T12, edCases).filter(({ id, r }) => { const pk = r.handoff ? [].concat(r.handoff.to || [], r.handoff.notify || []).join(' ').toLowerCase() : ''; return !/\bed\b/i.test(r.message) && !/\bed\b|gojara/.test(pk); });
P(`Cases that require Ed: ${edCases.join(', ')}. Missed: v1.2 ${missEd12.length} | v1.3 ${missEd.length}`, ...missEd.map(({ id, r }) => `- ${id} r${r.run}`), '');

// ---- 5. capability -----------------------------------------------------------------
P('## 5. Capability violations', '');
const capRules = ['CAPABILITY'];
const c12 = audit(T12, teamIds, capRules).concat(audit(A12, amIds, capRules));
const c13 = audit(T13, teamIds, capRules).concat(audit(A13, amIds, capRules));
const capJ = (set, ids) => runsIn(set, ids).filter(({ r }) => confirmed(r, ['CF_CAPABILITY_CLAIM']).length);
P('| Measure (both suites, 64 replies) | v1.2 | v1.3 |', '|---|---|---|');
P(`| capability claims in sent replies (current guard) | ${c12.length} | ${c13.length} |`);
P(`| judges confirmed CF_CAPABILITY_CLAIM | ${capJ(T12, teamIds).length + capJ(A12, amIds).length} | ${capJ(T13, teamIds).length + capJ(A13, amIds).length} |`);
P(`| first drafts with a capability claim the guard caught (v1.3) | n/a | ${runsIn(T13, teamIds).concat(runsIn(A13, amIds)).filter(({ r }) => (r.guard.capability_first || []).length).length} |`, '');
for (const h of c13) P(`- v1.3 sent ${h.id} r${h.run}: "${h.sentence}"`);
for (const { id, r } of capJ(T13, teamIds).concat(capJ(A13, amIds))) P(`- v1.3 judge-confirmed ${id} r${r.run}: ${(confirmed(r, ['CF_CAPABILITY_CLAIM'])[0].flags[0] || {}).evidence || ''}`);
P('');

// ---- 6. unsupported legal / governance ------------------------------------------------
P('## 6. Unsupported legal or governance claims', '');
const lgRules = ['UNSOURCED_LEGAL', 'TYPICAL_AS_RULE', 'INVENTED_ORG_ROLE', 'AUTHORITY'];
const l12 = audit(T12, teamIds, lgRules).concat(audit(A12, amIds, lgRules));
const l13 = audit(T13, teamIds, lgRules).concat(audit(A13, amIds, lgRules));
const lgCodes = ['CF_INVENTED_LEGAL_AUTHORITY', 'CF_INVENTED_GOVDOC_RULE', 'CF_INVENTED_ORG_ROLE', 'CF_UNAUTHORIZED_DECISION'];
const lgJ = (set, ids) => runsIn(set, ids).filter(({ r }) => confirmed(r, lgCodes).length);
P('| Measure (both suites) | v1.2 | v1.3 |', '|---|---|---|');
P(`| guard-detected in sent replies (unsourced law, typical norm, invented role or body, self-authority) | ${l12.length} | ${l13.length} |`);
P(`| replies with a judge-confirmed legal/governance/authority failure | ${lgJ(T12, teamIds).length + lgJ(A12, amIds).length} | ${lgJ(T13, teamIds).length + lgJ(A13, amIds).length} |`, '');
for (const h of l13) P(`- v1.3 guard ${h.id} r${h.run} ${h.rule}: "${h.sentence}"`);
for (const { id, r } of lgJ(T13, teamIds).concat(lgJ(A13, amIds))) for (const f of confirmed(r, lgCodes)) P(`- v1.3 judges ${id} r${r.run} ${f.code}: ${(f.flags[0] || {}).evidence || ''}`);
P('');

// ---- 7-9. relationship, consistency, judges ---------------------------------------------
function tally(set, ids) {
  const t = Object.fromEntries(DIMS.map((d) => [d, { pass: 0, needs_review: 0, fail: 0 }]));
  let splits = 0, cStrict = 0, runs = 0, words = 0, inc = 0, conf = 0;
  const rank = { pass: 0, needs_review: 1, fail: 2 };
  for (const id of ids) { if (!set[id]) continue; inc += Object.values(set[id].consistency || {}).filter((v) => !v.consistent).length; }
  for (const { r } of runsIn(set, ids)) {
    runs++; words += wc(r.message); conf += (r.critical_failures || []).filter((f) => f.status === 'confirmed').length;
    for (const d of DIMS) { const x = r.dimensions[d]; t[d][x.verdict]++; const b = x.by_judge || {}; if (b[J[0]] && b[J[1]] && b[J[0]].verdict !== b[J[1]].verdict) { splits++; if (rank[b[J[0]].verdict] > rank[b[J[1]].verdict]) cStrict++; } }
  }
  return { t, splits, cStrict, runs, words: Math.round(words / (runs || 1)), inc, conf };
}
const tt12 = tally(T12, teamIds), tt13 = tally(T13, teamIds), ta12 = tally(A12, amIds), ta13 = tally(A13, amIds);
P('## 7-9. Relationship quality, cross-run consistency, judge disagreements', '');
P('| Measure | team v1.2 | team v1.3 | existing v1.2 | existing v1.3 |', '|---|---|---|---|---|');
for (const d of DIMS) P(`| ${d} pass / fail (of 32) | ${tt12.t[d].pass} / ${tt12.t[d].fail} | ${tt13.t[d].pass} / ${tt13.t[d].fail} | ${ta12.t[d].pass} / ${ta12.t[d].fail} | ${ta13.t[d].pass} / ${ta13.t[d].fail} |`);
P(`| confirmed critical failures | ${tt12.conf} | ${tt13.conf} | ${ta12.conf} | ${ta13.conf} |`);
P(`| cross-run inconsistent verdicts (of 64) | ${tt12.inc} | ${tt13.inc} | ${ta12.inc} | ${ta13.inc} |`);
P(`| judge split verdicts (of 128) | ${tt12.splits} | ${tt13.splits} | ${ta12.splits} | ${ta13.splits} |`);
P(`| ...Claude stricter / GPT stricter | ${tt12.cStrict} / ${tt12.splits - tt12.cStrict} | ${tt13.cStrict} / ${tt13.splits - tt13.cStrict} | ${ta12.cStrict} / ${ta12.splits - ta12.cStrict} | ${ta13.cStrict} / ${ta13.splits - ta13.cStrict} |`);
P(`| mean words | ${tt12.words} | ${tt13.words} | ${ta12.words} | ${ta13.words} |`, '');
P('### Judge disagreements in v1.3 (dimension, Claude vs GPT)', '');
for (const [label, set, ids] of [['team', T13, teamIds], ['existing', A13, amIds]]) {
  for (const { id, r } of runsIn(set, ids)) for (const d of DIMS) {
    const b = r.dimensions[d].by_judge || {};
    if (b[J[0]] && b[J[1]] && b[J[0]].verdict !== b[J[1]].verdict) P(`- [${label}] ${id} r${r.run} ${d}: Claude ${b[J[0]].verdict} / GPT ${b[J[1]].verdict}. C: ${b[J[0]].explanation} G: ${b[J[1]].explanation}`);
  }
}
P('');

// ---- existing cases table ---------------------------------------------------------------
P('## Existing cases: v1.2 -> v1.3 (run 1/run 2)', '');
P('| Case | expertise | judgment | relationship | execution |', '|---|---|---|---|---|');
for (const id of amIds) P(`| ${id} ${A13[id].title} | ${DIMS.map((d) => `${runsOf(A12[id], d)} -> ${runsOf(A13[id], d)}`).join(' | ')} |`);
P('');

// ---- guard / gate revisions ---------------------------------------------------------------
P('## Revisions (guard or release gate): first draft vs sent', '');
for (const [label, set, ids] of [['team', T13, teamIds], ['existing', A13, amIds]]) {
  for (const { id, r } of runsIn(set, ids).filter(({ r }) => r.guard && r.guard.revised)) {
    P(`### [${label}] ${id} run ${r.run}`, '', `Caught: ${[...r.guard.first_violations.map((v) => `${v.rule} ("${v.sentence}")`), ...(r.guard.gate_first || []).map((p) => `HANDOFF_REQUIRED (${p.detail})`)].join('; ')}`, '', '**First draft:**', '', quote(r.guard.first_draft), '', '**Sent:**', '', quote(r.message), '', `After revision: guard ${r.guard.final_violations.map((v) => v.rule).join(', ') || 'clean'}; release ${r.guard.release.status}`, '');
  }
}

// ---- raw ------------------------------------------------------------------------------------
P('## Raw responses, verbatim (v1.3)', '');
for (const [label, set, ids] of [['Team-routing', T13, teamIds], ['Existing cases', A13, amIds]]) {
  P(`### ${label}`, '');
  for (const id of ids) {
    P(`#### ${id}: ${set[id].title}${set[id].agent ? ` (${set[id].agent})` : ''}`, '');
    for (const r of set[id].runs.filter((x) => x.message)) {
      const o = r.guard && r.guard.owner;
      P(`**Run ${r.run}** · ${wc(r.message)} words · ${DIMS.map((d) => `${d} ${s(r.dimensions[d].verdict)}`).join(', ')} · owner: ${o ? `${o.owner_class}/${o.owner}` : '-'} · release: ${r.guard ? r.guard.release.status : '-'} · critical: ${(r.critical_failures || []).map((f) => `${f.code} (${f.status})`).join(', ') || 'none'}`, '', quote(r.message), '');
      if (r.handoff) P(`Handoff package: \`${JSON.stringify(r.handoff)}\``, '');
      if ((r.commitments || []).length) P(`Commitments: \`${JSON.stringify(r.commitments)}\``, '');
    }
  }
}
process.stdout.write(out.join('\n') + '\n');
