#!/usr/bin/env node
// academy/tools/v1_4_review.js - data for the v1.4 (hard guards live) review.
//   node academy/tools/v1_4_review.js > academy/reports/sample-v1_4-review.data.md
const path = require('path');
const REP = path.join(__dirname, '..', 'reports');
const R = (f) => require(path.join(REP, f));
const idx = (r) => Object.fromEntries(r.results.map((c) => [c.case_id, c]));
const T13 = idx(R('sample-v1_3-team.json')), T14 = idx(R('sample-v1_4-team.json'));
const A13 = idx(R('sample-v1_3-candidate.json')), A14 = idx(R('sample-v1_4-candidate.json'));
const DIMS = ['expertise', 'judgment', 'relationship', 'execution'];
const J = ['anthropic:claude-sonnet-5', 'openai:gpt-5.6-terra'];
const HARD = ['FAKE_CREDENTIAL', 'UNRECORDED_NOW_ACTION', 'VENDOR_TERMINATION_NO_ED', 'PACKAGE_FACT_ALTERED', 'UNVERIFIED_ROUTING', 'UNSUPPORTED_AUTHORITY'];
const s = (v) => ({ pass: 'P', fail: 'F', needs_review: 'NR' }[v] || '-');
const wc = (t) => String(t || '').split(/\s+/).filter(Boolean).length;
const quote = (t) => String(t || '').split('\n').map((l) => `> ${l}`).join('\n');
const runsIn = (set) => Object.keys(set).flatMap((id) => set[id].runs.filter((r) => r.dimensions).map((r) => ({ id, r, suite: set[id].suite || 'amanda' })));
const out = []; const P = (...x) => out.push(...x);
const all14 = [...runsIn(T14), ...runsIn(A14)];

P('# v1.4 data: hard guards live (generated by academy/tools/v1_4_review.js)', '');

// 1. first-draft violations by type
const byType = {};
for (const { r } of all14) for (const v of (r.guard.first_violations || [])) byType[v.rule] = (byType[v.rule] || 0) + 1;
for (const { r } of all14) for (const p of (r.guard.gate_first || [])) byType[`GATE:${p.code}`] = (byType[`GATE:${p.code}`] || 0) + 1;
P('## 1. First-draft violations by type (64 replies)', '', '| Rule | First drafts | New hard guard? |', '|---|---|---|');
for (const [k, n] of Object.entries(byType).sort((a, b) => b[1] - a[1])) P(`| ${k} | ${n} | ${HARD.includes(k) || k === 'GATE:HO_NOT_TRACKED' ? 'yes' : ''} |`);
const drafts = all14.filter(({ r }) => (r.guard.first_violations || []).length || (r.guard.gate_first || []).length);
P('', `Replies whose first draft tripped at least one rule: ${drafts.length} of ${all14.length}.`, '');

// 2 + 3. rewrites that passed / held
const revised = all14.filter(({ r }) => r.guard.revised);
const passed = revised.filter(({ r }) => !(r.guard.final_violations || []).length && r.guard.release.status === 'released');
const held = all14.filter(({ r }) => r.guard.release.status === 'held');
const sentWith = all14.filter(({ r }) => r.guard.release.status !== 'held' && (r.guard.final_violations || []).length);
P('## 2-3. Rewrites that passed, replies held', '', '| Outcome | Replies |', '|---|---|');
P(`| revised once | ${revised.length} |`, `| revision cleared everything and was released | ${passed.length} |`, `| held by the release gate (never sent) | ${held.length} |`, `| released with a guard violation still present (production design: hold for review) | ${sentWith.length} |`, '');
for (const { id, r } of held) P(`- HELD ${id} r${r.run}: ${r.guard.release.problems.map((p) => p.detail).join('; ')}`);
for (const { id, r } of sentWith) P(`- STILL VIOLATING ${id} r${r.run}: ${r.guard.final_violations.map((v) => `${v.rule} "${String(v.sentence).slice(0, 110)}"`).join('; ')}`);
P('');

// 4. every hard-guard hit for manual false-positive review
P('## 4. Every new hard-guard hit on a first draft (for false-positive review)', '');
for (const { id, r } of all14) for (const v of (r.guard.first_violations || []).filter((x) => HARD.includes(x.rule))) P(`- ${id} r${r.run} **${v.rule}**: "${String(v.sentence).slice(0, 160)}" (${v.detail})`);
for (const { id, r } of all14) for (const p of (r.guard.gate_first || []).filter((x) => x.code === 'HO_NOT_TRACKED')) P(`- ${id} r${r.run} **GATE HO_NOT_TRACKED**: ${p.detail}`);
P('');

// 5-7. scores, relationship, consistency
function tally(set) {
  const t = Object.fromEntries(DIMS.map((d) => [d, { pass: 0, needs_review: 0, fail: 0 }])); let splits = 0, inc = 0, conf = 0, words = 0, n = 0;
  for (const id of Object.keys(set)) inc += Object.values(set[id].consistency || {}).filter((v) => !v.consistent).length;
  for (const { r } of runsIn(set)) { n++; words += wc(r.message); conf += (r.critical_failures || []).filter((f) => f.status === 'confirmed').length; for (const d of DIMS) { const x = r.dimensions[d]; t[d][x.verdict]++; const b = x.by_judge || {}; if (b[J[0]] && b[J[1]] && b[J[0]].verdict !== b[J[1]].verdict) splits++; } }
  return { t, splits, inc, conf, words: Math.round(words / (n || 1)), n };
}
const a = { t13: tally(T13), t14: tally(T14), a13: tally(A13), a14: tally(A14) };
P('## 5-7. Scores, relationship, consistency (v1.3 -> v1.4)', '', '| Measure | team v1.3 | team v1.4 | existing v1.3 | existing v1.4 |', '|---|---|---|---|---|');
for (const d of DIMS) P(`| ${d} pass / NR / fail | ${a.t13.t[d].pass}/${a.t13.t[d].needs_review}/${a.t13.t[d].fail} | ${a.t14.t[d].pass}/${a.t14.t[d].needs_review}/${a.t14.t[d].fail} | ${a.a13.t[d].pass}/${a.a13.t[d].needs_review}/${a.a13.t[d].fail} | ${a.a14.t[d].pass}/${a.a14.t[d].needs_review}/${a.a14.t[d].fail} |`);
P(`| confirmed critical failures | ${a.t13.conf} | ${a.t14.conf} | ${a.a13.conf} | ${a.a14.conf} |`, `| cross-run inconsistent (of 64) | ${a.t13.inc} | ${a.t14.inc} | ${a.a13.inc} | ${a.a14.inc} |`, `| judge split verdicts (of 128) | ${a.t13.splits} | ${a.t14.splits} | ${a.a13.splits} | ${a.a14.splits} |`, `| mean words | ${a.t13.words} | ${a.t14.words} | ${a.a13.words} | ${a.a14.words} |`, '');
const relOf = (list) => { const c = { pass: 0, needs_review: 0, fail: 0 }; for (const { r } of list) c[r.dimensions.relationship.verdict]++; return `${c.pass}/${c.needs_review}/${c.fail} (n=${list.length})`; };
P(`Relationship pass/NR/fail, v1.4: revised replies ${relOf(revised)}; replies not revised ${relOf(all14.filter(({ r }) => !r.guard.revised))}.`, '');

// 8. revision pairs for the robotic / less-useful review
P('## 8. Every guard revision: first draft vs sent', '');
for (const { id, r } of revised) {
  const w1 = wc(r.guard.first_draft), w2 = wc(r.message);
  P(`### ${id} run ${r.run} (${w1} -> ${w2} words; relationship ${s(r.dimensions.relationship.verdict)}, execution ${s(r.dimensions.execution.verdict)})`, '', `Caught: ${[...(r.guard.first_violations || []).map((v) => v.rule), ...(r.guard.gate_first || []).map((p) => 'GATE:' + p.code)].join(', ')}`, '', '**First draft:**', '', quote(r.guard.first_draft), '', '**Sent:**', '', quote(r.message), '');
}

// raw replies not revised, for completeness
P('## Raw replies (not revised)', '');
for (const { id, r } of all14.filter(({ r }) => !r.guard.revised)) P(`**${id} r${r.run}** · ${wc(r.message)} words · ${DIMS.map((d) => `${d} ${s(r.dimensions[d].verdict)}`).join(', ')} · release ${r.guard.release.status}`, '', quote(r.message), '');
process.stdout.write(out.join('\n') + '\n');
