-- ============================================================================
-- 501_conversion_builder_coverage.sql  (Ed 2026-10-08, GitHub issue #96)
-- ----------------------------------------------------------------------------
-- A configured community's accounting conversion brings its builder lots to the
-- builder rate and carries any deferred annual assessment correctly; after it,
-- the builder lots are billed forward by the program's cadence with no overlap
-- and no silent gap. GENERIC: every community fact (builder, annual assessment,
-- rates, accounts, deferral release, assessment year, cadence) comes from
-- configuration (migration 500: builder_assessment_programs,
-- community_assessment_rates, transfer_proration_builders) or from the approved
-- conversion plan. Nothing here names a community, a builder or an amount.
--
-- 1) conversion_reconciling_items: what a conversion found that does not
--    reconcile and must NOT be folded into anything (e.g. a residue left in a
--    deferral account outside the release schedule; a builder lot whose activity
--    does not show what it was billed). Written by EXECUTE, one row per (batch,
--    kind, key). APPEND ONLY: never deleted, never edited; the one change allowed
--    is open -> resolved, which records who, when and why (10+ characters). A
--    rerun of the conversion cannot remove one: a committed EXECUTE returns the
--    earlier result and writes nothing; an attempt that rolls back took its items
--    with it and the next attempt writes them again; a later batch for the same
--    community gets its own rows. Record ownership: association_record.
--
-- 2) builder_accrual_runs: one row per accrual run (staged -> posted).
--    builder_assessment_coverage.accrual_run_id now references it (RESTRICT).
--    Record ownership: association_record.
--
-- 3) onboarding_execute: the 498 body, plus, when the approved plan carries them:
--      * the builder coverage batch ({code}-BUILDER): its ledger rows dated the
--        cutover (tenure-stamped; a reduction is a correcting adjustment) and one
--        conversion coverage period per resolved builder lot, written pending and
--        posted with the {code}-BUILDER journal entry (already written with the
--        cutover-dated re-posts, so the cutoff trial balance still equals the
--        source exactly);
--      * the deferred-assessment release schedule (source conversion_balance,
--        approved by the person who approved the preflight, months generated by
--        the recognition engine's own trigger);
--      * the reconciling items.
--    VERIFY adds: builder ledger = the plan and = the entry's AR lines; one
--    coverage row per planned lot, all posted; the schedule total; the items; and
--    the new write counts against the plan summary (coalesce: plans without a
--    builder section verify exactly as before).
--    onboarding_execution_writes gains the tables/kinds these writes log under.
--
-- 4) Builder accrual: builder_accrual_plan (read-only), builder_accrual_stage
--    (draft batch + ledger rows + pending coverage), builder_accrual_finish (marks
--    a billing period posted once its journal entry, posted by
--    lib/accounting/builder_accrual.js through the normal posting path, equals
--    the period's coverage exactly). Completed periods of the program's cadence
--    only, within the community's assessment year; from the day after the last
--    covered day (or the builder's start); never past the run date; the period
--    ending the assessment year carries the rounding true-up the coverage guard
--    demands. Blocked lots are listed, never skipped silently.
--    ACTIVATION is an explicit post-conversion step: activate_builder_accrual
--    (who, when) is refused until the community's conversion is posted, and
--    builder_accrual_stage refuses until it is activated. The scheduler job
--    (builder_assessment_accrual) is also OFF unless SCHEDULER_ENABLED names it.
--
-- 5) builder_coverage_status(community, as_of): per builder lot, covered through
--    vs expected through (the cadence, 5 days' grace), whether the accrual is
--    activated, and the open reconciling items: the AR email, the Home Sales card
--    and the Operations Feed read this one function. Five days after an
--    assessment year ends, a lot not covered through its last day is RED.
--
-- Requires 500 (builder_assessment_coverage). Changes no existing row.
-- ============================================================================
BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Reconciling items
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversion_reconciling_items (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id          uuid NOT NULL,
  community_id      uuid NOT NULL,
  execution_id      uuid,
  kind              text NOT NULL,
  item_key          text NOT NULL,
  account_number    text,
  property_id       uuid,
  amount_cents      bigint NOT NULL,
  detail            jsonb NOT NULL DEFAULT '{}'::jsonb,
  status            text NOT NULL DEFAULT 'open',
  created_by        text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  resolved_by       text,
  resolved_at       timestamptz,
  resolution_note   text,
  resolution_journal_entry_id uuid,
  CONSTRAINT conversion_reconciling_items_batch_fk FOREIGN KEY (batch_id) REFERENCES conversion_batches(id) ON DELETE RESTRICT,
  CONSTRAINT conversion_reconciling_items_community_fk FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE RESTRICT,
  CONSTRAINT conversion_reconciling_items_property_fk FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE RESTRICT,
  CONSTRAINT conversion_reconciling_items_je_fk FOREIGN KEY (resolution_journal_entry_id) REFERENCES journal_entries(id) ON DELETE RESTRICT,
  CONSTRAINT conversion_reconciling_items_kind_check CHECK (kind IN ('deferral_residue', 'builder_position_unresolved')),
  CONSTRAINT conversion_reconciling_items_status_check CHECK (status IN ('open', 'resolved')),
  CONSTRAINT conversion_reconciling_items_resolution_check CHECK (
    (status = 'open' AND resolved_by IS NULL AND resolved_at IS NULL AND resolution_note IS NULL AND resolution_journal_entry_id IS NULL)
    OR (status = 'resolved' AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND length(btrim(coalesce(resolution_note, ''))) >= 10)),
  CONSTRAINT conversion_reconciling_items_unique UNIQUE (batch_id, kind, item_key)
);
CREATE INDEX IF NOT EXISTS idx_conversion_reconciling_items_open ON conversion_reconciling_items (community_id) WHERE status = 'open';
COMMENT ON TABLE conversion_reconciling_items IS 'association_record: what a conversion found that does not reconcile and was carried separately (never folded in). Append-only; open -> resolved with who/when/why.';

CREATE OR REPLACE FUNCTION conversion_reconciling_items_guard() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'a reconciling item is never deleted; resolve it with a note (item %)', OLD.id; END IF;
  IF (NEW.id, NEW.batch_id, NEW.community_id, NEW.execution_id, NEW.kind, NEW.item_key, NEW.account_number, NEW.property_id, NEW.amount_cents, NEW.detail, NEW.created_by, NEW.created_at)
     IS DISTINCT FROM
     (OLD.id, OLD.batch_id, OLD.community_id, OLD.execution_id, OLD.kind, OLD.item_key, OLD.account_number, OLD.property_id, OLD.amount_cents, OLD.detail, OLD.created_by, OLD.created_at) THEN
    RAISE EXCEPTION 'a reconciling item is fixed once recorded; only its resolution can be added';
  END IF;
  IF OLD.status = 'resolved' THEN RAISE EXCEPTION 'a resolved reconciling item is final'; END IF;
  IF NEW.status <> 'resolved' THEN RAISE EXCEPTION 'the only change to an open reconciling item is resolving it'; END IF;
  RETURN NEW;
END;
$fn$;
DROP TRIGGER IF EXISTS trg_conversion_reconciling_items_guard ON conversion_reconciling_items;
CREATE TRIGGER trg_conversion_reconciling_items_guard BEFORE UPDATE OR DELETE ON conversion_reconciling_items
  FOR EACH ROW EXECUTE FUNCTION conversion_reconciling_items_guard();
GRANT SELECT, INSERT, UPDATE ON conversion_reconciling_items TO service_role;

-- ---------------------------------------------------------------------------
-- 2) Accrual runs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS builder_accrual_runs (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  community_id  uuid NOT NULL,
  through_date  date NOT NULL,
  status        text NOT NULL DEFAULT 'staged',
  batch_id      uuid,
  plan          jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by    text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  posted_at     timestamptz,
  CONSTRAINT builder_accrual_runs_community_fk FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE RESTRICT,
  CONSTRAINT builder_accrual_runs_batch_fk FOREIGN KEY (batch_id) REFERENCES transaction_upload_batches(id) ON DELETE RESTRICT,
  CONSTRAINT builder_accrual_runs_status_check CHECK (status IN ('staged', 'posted')),
  CONSTRAINT builder_accrual_runs_posted_check CHECK (status <> 'posted' OR posted_at IS NOT NULL)
);
-- One unfinished run per community: a retry finishes it, never starts a second.
CREATE UNIQUE INDEX IF NOT EXISTS uq_builder_accrual_runs_staged ON builder_accrual_runs (community_id) WHERE status = 'staged';
COMMENT ON TABLE builder_accrual_runs IS 'association_record: one builder-assessment accrual run (staged -> posted).';
CREATE OR REPLACE FUNCTION builder_accrual_runs_guard() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'an accrual run is never deleted'; END IF;
  IF (NEW.id, NEW.community_id, NEW.through_date, NEW.batch_id, NEW.plan, NEW.created_by, NEW.created_at)
     IS DISTINCT FROM (OLD.id, OLD.community_id, OLD.through_date, OLD.batch_id, OLD.plan, OLD.created_by, OLD.created_at) THEN
    RAISE EXCEPTION 'an accrual run is fixed once staged';
  END IF;
  IF NEW.status <> OLD.status AND NOT (OLD.status = 'staged' AND NEW.status = 'posted') THEN
    RAISE EXCEPTION 'an accrual run cannot move from % to %', OLD.status, NEW.status;
  END IF;
  RETURN NEW;
END;
$fn$;
DROP TRIGGER IF EXISTS trg_builder_accrual_runs_guard ON builder_accrual_runs;
CREATE TRIGGER trg_builder_accrual_runs_guard BEFORE UPDATE OR DELETE ON builder_accrual_runs FOR EACH ROW EXECUTE FUNCTION builder_accrual_runs_guard();
GRANT SELECT, INSERT, UPDATE ON builder_accrual_runs TO service_role;

ALTER TABLE builder_assessment_coverage DROP CONSTRAINT IF EXISTS builder_assessment_coverage_accrual_run_fk;
ALTER TABLE builder_assessment_coverage ADD CONSTRAINT builder_assessment_coverage_accrual_run_fk
  FOREIGN KEY (accrual_run_id) REFERENCES builder_accrual_runs(id) ON DELETE RESTRICT;

-- ---------------------------------------------------------------------------
-- 3a) The execution write log learns the new tables / kinds
-- ---------------------------------------------------------------------------
ALTER TABLE onboarding_execution_writes DROP CONSTRAINT IF EXISTS onboarding_execution_writes_table_name_check;
ALTER TABLE onboarding_execution_writes ADD CONSTRAINT onboarding_execution_writes_table_name_check
  CHECK (table_name IN ('journal_entries','transaction_upload_batches','homeowner_transactions','ap_invoices','communities','conversion_batches',
                        'builder_assessment_coverage','recognition_schedules','conversion_reconciling_items'));
ALTER TABLE onboarding_execution_writes DROP CONSTRAINT IF EXISTS onboarding_execution_writes_write_kind_check;
ALTER TABLE onboarding_execution_writes ADD CONSTRAINT onboarding_execution_writes_write_kind_check
  CHECK (write_kind IN ('opening_je','neutralize_je','repost_je','supersede_je','ar_opening_batch','ar_opening_row',
                        'revert_ar_batch','ap_opening_invoice','cutover_date','conversion_batch',
                        'builder_batch','builder_row','builder_coverage','deferral_schedule','reconciling_item'));

-- ---------------------------------------------------------------------------
-- 3b) onboarding_execute (498 body + the builder / schedule / reconciling blocks)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION onboarding_execute(p_batch UUID, p_completion UUID, p_preflight_sha256 TEXT, p_actor_kind TEXT, p_actor_id TEXT)
RETURNS JSONB LANGUAGE plpgsql AS $fn$
DECLARE
  bt conversion_batches%ROWTYPE; c onboarding_stage_events%ROWTYPE; ex onboarding_executions%ROWTYPE;
  rep JSONB; plan JSONB; w JSONB; pre JSONB; ab JSONB; r JSONB; proof_plan JSONB;
  code TEXT; comm UUID; cutoff DATE; cutover DATE; why TEXT; bad TEXT; prov TEXT;
  appr UUID; adv UUID; done UUID; ar_batch UUID := gen_random_uuid(); row_id UUID; je UUID;
  exec_id UUID := gen_random_uuid(); n BIGINT; v BIGINT; i INT;
  n_open INT; n_neut INT; n_repost INT; n_sup INT; n_rev INT; n_ar INT; n_ap INT; n_post BIGINT;
  ar_recv BIGINT; ar_cur BIGINT; ar_prior BIGINT; counts JSONB; proof JSONB; controls JSONB; old_cutover DATE;
  -- 501
  bb JSONB; b_batch UUID; b_je UUID; b_je_ref TEXT; n_bcov INT := 0; n_brow INT := 0; n_sched INT := 0; n_items INT := 0;
  b_ledger BIGINT; b_gl BIGINT; txn UUID; cov_id UUID; appr_actor TEXT; sched_id UUID;
BEGIN
  PERFORM onboarding_assert_actor(p_actor_kind, p_actor_id, TRUE);
  SELECT * INTO bt FROM conversion_batches WHERE id = p_batch FOR UPDATE;
  IF NOT FOUND OR bt.onboarding_stage IS NULL THEN RAISE EXCEPTION 'onboarding: no such engine batch' USING ERRCODE = 'check_violation'; END IF;

  -- Idempotent retry: a committed execution is returned, never repeated.
  SELECT * INTO ex FROM onboarding_executions WHERE batch_id = p_batch AND status = 'committed';
  IF FOUND THEN
    IF ex.preflight_completion_id = p_completion AND ex.preflight_sha256 = p_preflight_sha256 THEN
      RETURN jsonb_build_object('status', 'already_executed', 'execution_id', ex.id, 'execute_completion_id', ex.execute_completion_id,
                                'write_counts', ex.write_counts, 'proof', ex.proof, 'rows_written_now', 0);
    END IF;
    RAISE EXCEPTION 'onboarding: execute refused: this batch was already executed (execution %) from another preflight', ex.id USING ERRCODE = 'check_violation';
  END IF;
  IF bt.onboarding_stage <> 'preflight' THEN
    RAISE EXCEPTION 'onboarding: execute refused: execute starts from the preflight stage; the batch is in %', bt.onboarding_stage USING ERRCODE = 'check_violation';
  END IF;

  -- The exact CURRENT preflight result, approved by a human for exactly this hash.
  SELECT * INTO c FROM onboarding_stage_events WHERE id = p_completion AND batch_id = p_batch AND event_type = 'stage_completed' AND stage = 'preflight';
  IF NOT FOUND THEN RAISE EXCEPTION 'onboarding: execute refused: not a preflight result of this batch' USING ERRCODE = 'check_violation'; END IF;
  why := onboarding_completion_gate(c.id);
  IF why IS NOT NULL THEN RAISE EXCEPTION 'onboarding: execute refused: %', why USING ERRCODE = 'check_violation'; END IF;
  IF p_preflight_sha256 IS NULL OR bt.approved_preflight_sha256 IS DISTINCT FROM p_preflight_sha256 THEN
    RAISE EXCEPTION 'onboarding: execute refused: % is not the approved preflight hash', coalesce(p_preflight_sha256, '(none)') USING ERRCODE = 'check_violation';
  END IF;
  SELECT id, actor_id INTO appr, appr_actor FROM onboarding_stage_events WHERE batch_id = p_batch AND event_type = 'preflight_approved' AND actor_kind = 'human'
     AND completion_event_id = c.id AND preflight_sha256 = p_preflight_sha256 ORDER BY seq DESC LIMIT 1;
  IF appr IS NULL THEN RAISE EXCEPTION 'onboarding: execute refused: no human approval of that hash for the current preflight result' USING ERRCODE = 'check_violation'; END IF;
  rep := c.result->'summary'->'preflight_report';
  IF rep IS NULL OR rep->>'format' IS DISTINCT FROM 'trusted.onboarding.preflight/v2' OR rep->'plan'->'writes' IS NULL THEN
    RAISE EXCEPTION 'onboarding: execute refused: the preflight result carries no conversion write contract' USING ERRCODE = 'check_violation';
  END IF;
  IF rep->'batch'->>'batch_code' IS DISTINCT FROM bt.batch_code THEN RAISE EXCEPTION 'onboarding: execute refused: the report is for another batch' USING ERRCODE = 'check_violation'; END IF;
  -- Without waivers the approved hash IS the recorded report's hash. (With waivers the approved report
  -- carries their dispositions; the service rebuilds and compares it before calling.)
  IF NOT EXISTS (SELECT 1 FROM onboarding_stage_events wv WHERE wv.completion_event_id = c.id AND wv.event_type = 'control_waived')
     AND c.result->'summary'->>'preflight_sha256' IS DISTINCT FROM p_preflight_sha256 THEN
    RAISE EXCEPTION 'onboarding: execute refused: the approved hash is not the recorded preflight report' USING ERRCODE = 'check_violation';
  END IF;

  plan := rep->'plan'; w := plan->'writes'; pre := plan->'preconditions'; ab := w->'ar_opening_batch'; proof_plan := plan->'proof_plan';
  bb := w->'builder_coverage_batch';
  code := bt.batch_code; comm := bt.community_id; cutoff := (plan->>'cutoff')::date; cutover := (plan->>'cutover')::date;
  IF cutoff IS DISTINCT FROM bt.as_of_date OR cutover IS DISTINCT FROM cutoff + 1 OR (w->'cutover_date'->>'to')::date IS DISTINCT FROM cutover THEN
    RAISE EXCEPTION 'onboarding: execute refused: the plan''s cutoff/cutover does not match the batch' USING ERRCODE = 'check_violation';
  END IF;

  -- ---------------------------------------------------------------- preconditions (live)
  IF NOT (bt.status IN (SELECT jsonb_array_elements_text(pre->'batch_status_in'))) THEN
    RAISE EXCEPTION 'onboarding: execute refused: batch status % is not postable', bt.status USING ERRCODE = 'check_violation';
  END IF;
  SELECT count(*) INTO n FROM journal_entries WHERE community_id = comm AND left(reference, length(code)) = code;
  IF n <> 0 THEN RAISE EXCEPTION 'onboarding: execute refused: % journal entr(ies) with reference % already exist', n, code || '*' USING ERRCODE = 'check_violation'; END IF;
  SELECT gl_cutover_date INTO old_cutover FROM communities WHERE id = comm;
  IF old_cutover IS DISTINCT FROM (pre->>'gl_cutover_date_is')::date THEN
    RAISE EXCEPTION 'onboarding: execute refused: the GL cutover date is %, the plan expected %', old_cutover, pre->>'gl_cutover_date_is' USING ERRCODE = 'check_violation';
  END IF;
  n_sup := jsonb_array_length(w->'supersede_journal_entries');
  SELECT count(*) INTO n FROM jsonb_array_elements(w->'supersede_journal_entries') x
    JOIN journal_entries j ON j.id = (x->>'id')::uuid AND j.community_id = comm AND j.status = 'posted';
  IF n <> n_sup OR n_sup <> (pre->'supersede_set'->>'count')::int THEN
    RAISE EXCEPTION 'onboarding: execute refused: % of % entries to supersede are still posted', n, n_sup USING ERRCODE = 'check_violation';
  END IF;
  n_neut := jsonb_array_length(w->'neutralize_journal_entries');
  SELECT count(*) INTO n FROM jsonb_array_elements(w->'neutralize_journal_entries') x
    -- 498: a neutralize target is any COUNTED entry (posted, or voided with its reversal: the same rule as the
    -- trial balance above and below). A void pair straddling the cutoff has a voided original that still counts.
    JOIN journal_entries j ON j.id = (x->>'original_je_id')::uuid AND j.community_id = comm
     AND (j.status = 'posted' OR (j.status = 'voided' AND j.void_reversal_je_id IS NOT NULL))
     AND j.posting_date = (x->>'posting_date')::date AND j.total_debits_cents = (x->>'total_debits_cents')::bigint
     AND (SELECT count(*) FROM journal_entry_lines jl WHERE jl.journal_entry_id = j.id) = jsonb_array_length(x->'lines');
  IF n <> n_neut OR n_neut <> (pre->'neutralize_set'->>'count')::int THEN
    RAISE EXCEPTION 'onboarding: execute refused: % of % entries to neutralize are unchanged since the preflight', n, n_neut USING ERRCODE = 'check_violation';
  END IF;
  n_repost := jsonb_array_length(w->'repost_journal_entries');
  n_rev := jsonb_array_length(w->'revert_ar_batches');
  SELECT count(*) INTO n FROM jsonb_array_elements(w->'revert_ar_batches') x
    JOIN transaction_upload_batches t ON t.id = (x->>'id')::uuid AND t.community_id = comm AND t.status = 'committed';
  IF n <> n_rev THEN RAISE EXCEPTION 'onboarding: execute refused: % of % legacy ledger batches are still committed', n, n_rev USING ERRCODE = 'check_violation'; END IF;
  SELECT count(*), coalesce(sum(total_debits_cents), 0) INTO n, v FROM journal_entries
   WHERE community_id = comm AND posting_date >= cutover AND (status = 'posted' OR (status = 'voided' AND void_reversal_je_id IS NOT NULL));
  IF n <> (pre->'post_cutover_entries'->>'count')::bigint OR v <> (pre->'post_cutover_entries'->>'debits_cents')::bigint THEN
    RAISE EXCEPTION 'onboarding: execute refused: post-cutover activity changed since the preflight (% entries, % debits)', n, v USING ERRCODE = 'check_violation';
  END IF;
  SELECT string_agg(x->>'reference', ', ') INTO bad
    FROM (SELECT x FROM jsonb_array_elements(w->'opening_journal_entries') x UNION ALL SELECT x FROM jsonb_array_elements(w->'neutralize_journal_entries') x
          UNION ALL SELECT x FROM jsonb_array_elements(w->'repost_journal_entries') x) q
   WHERE NOT EXISTS (SELECT 1 FROM accounting_periods p WHERE p.id = (x->>'period_id')::uuid AND p.community_id = comm
                       AND p.period_start <= (x->>'posting_date')::date AND p.period_end >= (x->>'posting_date')::date AND p.status IN ('open','reopened'));
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'onboarding: execute refused: no open accounting period for %', bad USING ERRCODE = 'check_violation'; END IF;
  -- 501: no builder lot may already carry coverage for the conversion year (the conversion writes the first period).
  IF bb IS NOT NULL THEN
    SELECT string_agg(x->>'street_address', ', ') INTO bad FROM jsonb_array_elements(bb->'rows') x
     WHERE EXISTS (SELECT 1 FROM builder_assessment_coverage cv WHERE cv.tenure_id = (x->>'tenure_id')::uuid AND cv.fiscal_year = (x->>'fiscal_year')::int AND cv.status <> 'voided');
    IF bad IS NOT NULL THEN RAISE EXCEPTION 'onboarding: execute refused: builder coverage already exists for %', bad USING ERRCODE = 'check_violation'; END IF;
  END IF;

  -- ------------------------------------------------- enter execute; the write lock opens
  INSERT INTO onboarding_stage_events (batch_id, event_type, stage, to_stage, completion_event_id, actor_kind, actor_id)
  VALUES (p_batch, 'stage_advanced', 'preflight', 'execute', c.id, 'human', p_actor_id)      -- validate trigger: next stage, latest result, gate
  RETURNING id INTO adv;
  UPDATE conversion_batches SET onboarding_stage = 'execute', write_locked = FALSE WHERE id = p_batch;   -- guard: human advance + approved hash for this result
  prov := format('onboarding %s · batch %s · preflight %s · execution %s', code, p_batch, c.id, exec_id);

  -- ---------------------------------------------------------------- journal entries
  n_open := jsonb_array_length(w->'opening_journal_entries');
  FOR r IN SELECT x FROM jsonb_array_elements(w->'opening_journal_entries') x LOOP PERFORM onboarding_exec_post_je(exec_id, p_batch, comm, r, 'opening_je', prov); END LOOP;
  FOR r IN SELECT x FROM jsonb_array_elements(w->'neutralize_journal_entries') x LOOP PERFORM onboarding_exec_post_je(exec_id, p_batch, comm, r, 'neutralize_je', prov); END LOOP;
  FOR r IN SELECT x FROM jsonb_array_elements(w->'repost_journal_entries') x LOOP PERFORM onboarding_exec_post_je(exec_id, p_batch, comm, r, 'repost_je', prov); END LOOP;

  FOR r IN SELECT x FROM jsonb_array_elements(w->'supersede_journal_entries') x LOOP
    UPDATE journal_entries SET status = 'superseded', superseded_at = now(), superseded_by_conversion = code,
           superseded_reason = (r->'set'->>'superseded_reason') || ' [' || prov || ']'
     WHERE id = (r->>'id')::uuid AND community_id = comm AND status = 'posted';
    GET DIAGNOSTICS n = ROW_COUNT;
    IF n <> 1 THEN RAISE EXCEPTION 'onboarding execute: % could not be superseded', r->>'id' USING ERRCODE = 'check_violation'; END IF;
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, before, after)
    VALUES (exec_id, p_batch, 'journal_entries', (r->>'id')::uuid, 'update', 'supersede_je', r->>'reference', jsonb_build_object('status', 'posted'), jsonb_build_object('status', 'superseded'));
  END LOOP;

  -- ------------------------------------------------------------ homeowner ledger
  n_ar := jsonb_array_length(ab->'rows');
  INSERT INTO transaction_upload_batches (id, management_company_id, community_id, period_label, as_of_date, source_filename, source_format, row_count, account_count,
                                          total_charges_cents, total_payments_cents, status, uploaded_by, committed_at, min_transaction_date, max_transaction_date, notes)
  VALUES (ar_batch, (ab->>'management_company_id')::uuid, comm, ab->>'period_label', (ab->>'as_of_date')::date, ab->>'key', 'manual', n_ar, (ab->>'account_count')::int,
          (SELECT coalesce(sum((x->>'amount_cents')::bigint), 0) FROM jsonb_array_elements(ab->'rows') x WHERE (x->>'amount_cents')::bigint > 0),
          (SELECT coalesce(-sum((x->>'amount_cents')::bigint), 0) FROM jsonb_array_elements(ab->'rows') x WHERE (x->>'amount_cents')::bigint < 0),
          'committed', ab->>'uploaded_by', now(), (ab->>'as_of_date')::date, (ab->>'as_of_date')::date, 'Conversion opening homeowner balances · ' || prov);
  INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
  VALUES (exec_id, p_batch, 'transaction_upload_batches', ar_batch, 'insert', 'ar_opening_batch', ab->>'key', jsonb_build_object('row_count', n_ar, 'status', 'committed'));
  i := 0;
  FOR r IN SELECT x FROM jsonb_array_elements(ab->'rows') x LOOP
    i := i + 1; row_id := gen_random_uuid();
    INSERT INTO homeowner_transactions (id, source_batch_id, source_row_index, community_id, vantaca_account_id, property_id, tenure_id, transaction_date,
                                        description, txn_type, charge_category, amount_cents, raw_row_jsonb, notes)
    VALUES (row_id, ar_batch, i, comm, r->>'vantaca_account_id', (r->>'property_id')::uuid, (r->>'tenure_id')::uuid, (r->>'transaction_date')::date,
            r->>'description', r->>'txn_type', r->>'charge_category', (r->>'amount_cents')::bigint,
            coalesce(r->'raw_row', '{}'::jsonb) || jsonb_build_object('onboarding', jsonb_build_object('batch_id', p_batch, 'preflight_completion_id', c.id, 'execution_id', exec_id,
                                                   'source_line_no', r->'source_line_no', 'prior_owner', coalesce((r->>'prior_owner')::boolean, false))),
            'source line ' || coalesce(r->>'source_line_no', '?') || ' · ' || prov);
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
    VALUES (exec_id, p_batch, 'homeowner_transactions', row_id, 'insert', 'ar_opening_row', ab->>'key' || ':' || i,
            jsonb_build_object('vantaca_account_id', r->>'vantaca_account_id', 'amount_cents', (r->>'amount_cents')::bigint, 'prior_owner', coalesce((r->>'prior_owner')::boolean, false)));
  END LOOP;
  FOR r IN SELECT x FROM jsonb_array_elements(w->'revert_ar_batches') x LOOP
    UPDATE transaction_upload_batches SET status = 'reverted', reverted_at = now(), replaced_by_batch_id = ar_batch,
           reverted_reason = (r->'set'->>'reverted_reason') || ' [' || prov || ']'
     WHERE id = (r->>'id')::uuid AND community_id = comm AND status = 'committed';
    GET DIAGNOSTICS n = ROW_COUNT;
    IF n <> 1 THEN RAISE EXCEPTION 'onboarding execute: legacy ledger batch % could not be reverted', r->>'id' USING ERRCODE = 'check_violation'; END IF;
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, before, after)
    VALUES (exec_id, p_batch, 'transaction_upload_batches', (r->>'id')::uuid, 'update', 'revert_ar_batch', r->>'id', jsonb_build_object('status', 'committed'), jsonb_build_object('status', 'reverted', 'replaced_by_batch_id', ar_batch));
  END LOOP;

  -- ------------------------------------------------- 501: builder assessments at the builder rate
  IF bb IS NOT NULL THEN
    b_je_ref := bb->>'journal_entry_reference';
    IF b_je_ref IS NOT NULL THEN
      SELECT id INTO b_je FROM journal_entries WHERE community_id = comm AND reference = b_je_ref AND status = 'posted';
      IF b_je IS NULL THEN RAISE EXCEPTION 'onboarding execute: the builder entry % was not written', b_je_ref USING ERRCODE = 'check_violation'; END IF;
    END IF;
    IF jsonb_array_length(bb->'rows') > 0 THEN
      b_batch := gen_random_uuid();
      n_brow := (SELECT count(*) FROM jsonb_array_elements(bb->'rows') x WHERE (x->>'ledger_amount_cents')::bigint <> 0);
      INSERT INTO transaction_upload_batches (id, management_company_id, community_id, period_label, as_of_date, source_filename, source_format, row_count, account_count,
                                              total_charges_cents, total_payments_cents, status, uploaded_by, committed_at, min_transaction_date, max_transaction_date, notes)
      VALUES (b_batch, (bb->>'management_company_id')::uuid, comm, bb->>'period_label', cutover, bb->>'key', 'manual', n_brow, n_brow,
              (SELECT coalesce(sum((x->>'ledger_amount_cents')::bigint), 0) FROM jsonb_array_elements(bb->'rows') x WHERE (x->>'ledger_amount_cents')::bigint > 0), 0,
              'committed', bb->>'uploaded_by', now(), cutover, cutover, 'Conversion builder assessments at the builder rate · ' || prov);
      INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
      VALUES (exec_id, p_batch, 'transaction_upload_batches', b_batch, 'insert', 'builder_batch', bb->>'key', jsonb_build_object('row_count', n_brow, 'status', 'committed'));
      i := 0;
      FOR r IN SELECT x FROM jsonb_array_elements(bb->'rows') x LOOP
        txn := NULL;
        IF (r->>'ledger_amount_cents')::bigint <> 0 THEN
          i := i + 1; txn := gen_random_uuid();
          INSERT INTO homeowner_transactions (id, source_batch_id, source_row_index, community_id, vantaca_account_id, trusted_account_number, property_id, tenure_id,
                                              transaction_date, description, txn_type, charge_category, amount_cents, reduction_source, raw_row_jsonb, notes)
          VALUES (txn, b_batch, i, comm, r->>'vantaca_account_id', r->>'account_number', (r->>'property_id')::uuid, (r->>'tenure_id')::uuid,
                  cutover, r->>'description', r->>'txn_type', 'assessment', (r->>'ledger_amount_cents')::bigint,
                  CASE WHEN (r->>'ledger_amount_cents')::bigint < 0 THEN 'correcting_adjustment' END,
                  jsonb_build_object('source', 'conversion_builder', 'batch_code', code, 'kind', r->>'kind', 'covered_from', r->>'covered_from', 'covered_through', r->>'covered_through',
                                     'onboarding', jsonb_build_object('batch_id', p_batch, 'preflight_completion_id', c.id, 'execution_id', exec_id)),
                  'builder ' || (r->>'kind') || ' · ' || prov);
          INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
          VALUES (exec_id, p_batch, 'homeowner_transactions', txn, 'insert', 'builder_row', bb->>'key' || ':' || (r->>'property_id'),
                  jsonb_build_object('property_id', r->>'property_id', 'amount_cents', (r->>'ledger_amount_cents')::bigint, 'kind', r->>'kind'));
        END IF;
        cov_id := gen_random_uuid();
        INSERT INTO builder_assessment_coverage (id, community_id, property_id, account_number, vantaca_account_id, tenure_id, builder_company_id, fiscal_year,
            year_start, year_end, covered_from, covered_through, days, days_in_year, annual_assessment_cents, builder_rate_pct, rate_source, base_amount_cents, rounding_true_up_cents,
            amount_cents, annual_billed_cents, legacy_evidence, source_type, conversion_batch_id, batch_id, homeowner_txn_id, status, created_by)
        VALUES (cov_id, comm, (r->>'property_id')::uuid, r->>'account_number', r->>'vantaca_account_id', (r->>'tenure_id')::uuid, (r->>'builder_company_id')::uuid,
            (r->>'fiscal_year')::int, (r->>'year_start')::date, (r->>'year_end')::date, (r->>'covered_from')::date, (r->>'covered_through')::date, (r->>'days')::int, (r->>'days_in_year')::int,
            (r->>'annual_assessment_cents')::bigint, (r->>'builder_rate_pct')::numeric, coalesce(r->'rate_source', '{}'::jsonb), (r->>'base_amount_cents')::bigint, 0,
            (r->>'base_amount_cents')::bigint, (r->>'annual_billed_cents')::bigint, r->'legacy_evidence', 'conversion', p_batch, b_batch, txn, 'pending', 'conversion:' || code);
        UPDATE builder_assessment_coverage SET status = 'posted', journal_entry_id = b_je, journal_entry_reference = b_je_ref WHERE id = cov_id;
        INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
        VALUES (exec_id, p_batch, 'builder_assessment_coverage', cov_id, 'insert', 'builder_coverage', bb->>'key' || ':coverage:' || (r->>'property_id'),
                jsonb_build_object('from', r->>'covered_from', 'through', r->>'covered_through', 'amount_cents', (r->>'base_amount_cents')::bigint, 'kind', r->>'kind'));
        n_bcov := n_bcov + 1;
      END LOOP;
    END IF;
  END IF;

  -- -------------------------------------------- 501: the deferred-assessment release schedule
  FOR r IN SELECT x FROM jsonb_array_elements(coalesce(w->'deferral_schedules', '[]'::jsonb)) x LOOP
    sched_id := gen_random_uuid();
    INSERT INTO recognition_schedules (id, community_id, schedule_type, description, balance_account_number, recognition_account_id, recognize_amount_cents,
        start_month, term_months, monthly_amount_cents, period_start, period_end, status, recognition_method, schedule_basis, source_type, source_id,
        explanation, created_by, approved_by, approved_at, notes)
    VALUES (sched_id, comm, r->>'schedule_type', r->>'description', r->>'balance_account_number', (r->>'recognition_account_id')::uuid, (r->>'recognize_amount_cents')::bigint,
        (r->>'start_month')::date, (r->>'term_months')::int, (r->>'monthly_amount_cents')::bigint, (r->>'period_start')::date, (r->>'period_end')::date,
        'active', r->>'recognition_method', r->>'schedule_basis', 'conversion_balance', p_batch,
        r->>'explanation', 'conversion:' || code, appr_actor, now(), 'Approved with the conversion preflight (approval ' || appr || ') · ' || prov);
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
    VALUES (exec_id, p_batch, 'recognition_schedules', sched_id, 'insert', 'deferral_schedule', code || ':deferral:' || (r->>'balance_account_number'),
            jsonb_build_object('recognize_amount_cents', (r->>'recognize_amount_cents')::bigint, 'term_months', (r->>'term_months')::int, 'start_month', r->>'start_month'));
    n_sched := n_sched + 1;
  END LOOP;

  -- ------------------------------------------------------------- 501: reconciling items
  FOR r IN SELECT x FROM jsonb_array_elements(coalesce(w->'reconciling_items', '[]'::jsonb)) x LOOP
    row_id := gen_random_uuid();
    INSERT INTO conversion_reconciling_items (id, batch_id, community_id, execution_id, kind, item_key, account_number, property_id, amount_cents, detail, created_by)
    VALUES (row_id, p_batch, comm, exec_id, r->>'kind', r->>'item_key', r->>'account_number', (r->>'property_id')::uuid, (r->>'amount_cents')::bigint,
            coalesce(r->'detail', '{}'::jsonb) || jsonb_build_object('recorded_by', prov), 'conversion:' || code);
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
    VALUES (exec_id, p_batch, 'conversion_reconciling_items', row_id, 'insert', 'reconciling_item', (r->>'kind') || ':' || (r->>'item_key'),
            jsonb_build_object('amount_cents', (r->>'amount_cents')::bigint));
    n_items := n_items + 1;
  END LOOP;

  -- -------------------------------------------------------------- open AP invoices
  n_ap := jsonb_array_length(w->'ap_opening_invoices');
  FOR r IN SELECT x FROM jsonb_array_elements(w->'ap_opening_invoices') x LOOP
    SELECT id INTO je FROM journal_entries WHERE community_id = comm AND reference = r->>'posting_journal_entry_reference';
    IF je IS NULL THEN RAISE EXCEPTION 'onboarding execute: AP invoice posting entry % was not written', r->>'posting_journal_entry_reference' USING ERRCODE = 'check_violation'; END IF;
    row_id := gen_random_uuid();
    INSERT INTO ap_invoices (id, community_id, vendor_id, vendor_invoice_number, invoice_date, subtotal_cents, total_cents, amount_paid_cents, status, posting_journal_entry_id, notes)
    VALUES (row_id, comm, (r->>'vendor_id')::uuid, r->>'vendor_invoice_number', (r->>'invoice_date')::date, (r->>'subtotal_cents')::bigint, (r->>'total_cents')::bigint,
            (r->>'amount_paid_cents')::bigint, r->>'status', je, 'Conversion opening AP; key ' || (r->>'idempotency_key') || ' · ' || prov);
    INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, after)
    VALUES (exec_id, p_batch, 'ap_invoices', row_id, 'insert', 'ap_opening_invoice', r->>'idempotency_key', jsonb_build_object('total_cents', (r->>'total_cents')::bigint, 'posting_journal_entry_id', je));
  END LOOP;

  -- ------------------------------------------------------------------ cutover date
  UPDATE communities SET gl_cutover_date = cutover WHERE id = comm AND gl_cutover_date IS NOT DISTINCT FROM old_cutover;
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION 'onboarding execute: the GL cutover date could not be set' USING ERRCODE = 'check_violation'; END IF;
  INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, before, after)
  VALUES (exec_id, p_batch, 'communities', comm, 'update', 'cutover_date', 'gl_cutover_date', jsonb_build_object('gl_cutover_date', old_cutover), jsonb_build_object('gl_cutover_date', cutover));

  -- -------------------------------------------------- VERIFY (mismatch -> rollback)
  bad := onboarding_exec_tb_diff(comm, cutoff, (SELECT x->'expected' FROM jsonb_array_elements(proof_plan) x WHERE x->>'check' = 'cutoff_trial_balance'));
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'onboarding execute: cutoff trial balance does not equal the source: %', bad USING ERRCODE = 'check_violation'; END IF;
  bad := onboarding_exec_tb_diff(comm, NULL, (SELECT x->'expected' FROM jsonb_array_elements(proof_plan) x WHERE x->>'check' = 'current_trial_balance'));
  IF bad IS NOT NULL THEN RAISE EXCEPTION 'onboarding execute: current trial balance does not equal the projection: %', bad USING ERRCODE = 'check_violation'; END IF;
  SELECT coalesce(sum(amount_cents) FILTER (WHERE txn_type <> 'credit'), 0),
         coalesce(sum(amount_cents) FILTER (WHERE txn_type = 'credit' AND NOT coalesce((raw_row_jsonb->'onboarding'->>'prior_owner')::boolean, false)), 0),
         coalesce(sum(amount_cents) FILTER (WHERE txn_type = 'credit' AND coalesce((raw_row_jsonb->'onboarding'->>'prior_owner')::boolean, false)), 0)
    INTO ar_recv, ar_cur, ar_prior FROM homeowner_transactions WHERE source_batch_id = ar_batch;
  IF ar_recv <> (ab->>'receivable_cents')::bigint OR ar_cur <> (ab->>'current_owner_prepaid_cents')::bigint OR ar_prior <> (ab->>'prior_owner_credit_cents')::bigint THEN
    RAISE EXCEPTION 'onboarding execute: homeowner ledger (% / % / %) does not equal the plan', ar_recv, ar_cur, ar_prior USING ERRCODE = 'check_violation';
  END IF;
  -- 501: the builder ledger = the plan = the builder entry's AR lines; every planned lot covered and posted.
  IF bb IS NOT NULL THEN
    SELECT coalesce(sum(amount_cents), 0) INTO b_ledger FROM homeowner_transactions WHERE b_batch IS NOT NULL AND source_batch_id = b_batch;
    -- the entry's receivable lines are the ones that name a lot (income / deferral lines name none)
    SELECT coalesce(sum(jl.debit_cents - jl.credit_cents), 0) INTO b_gl FROM journal_entry_lines jl
     WHERE b_je IS NOT NULL AND jl.journal_entry_id = b_je AND jl.property_id IS NOT NULL;
    IF b_ledger <> (bb->>'ledger_cents')::bigint OR b_gl <> b_ledger THEN
      RAISE EXCEPTION 'onboarding execute: builder ledger % / entry AR % do not equal the plan %', b_ledger, b_gl, bb->>'ledger_cents' USING ERRCODE = 'check_violation';
    END IF;
    SELECT count(*) INTO n FROM builder_assessment_coverage WHERE conversion_batch_id = p_batch AND status = 'posted' AND journal_entry_id IS NOT DISTINCT FROM b_je;
    IF n <> jsonb_array_length(bb->'rows') OR n <> n_bcov THEN
      RAISE EXCEPTION 'onboarding execute: % builder coverage periods posted, % planned', n, jsonb_array_length(bb->'rows') USING ERRCODE = 'check_violation';
    END IF;
  END IF;
  SELECT count(*), coalesce(sum(recognize_amount_cents), 0) INTO n, v FROM recognition_schedules WHERE source_type = 'conversion_balance' AND source_id = p_batch AND status = 'active';
  IF n <> n_sched OR v <> (SELECT coalesce(sum((x->>'recognize_amount_cents')::bigint), 0) FROM jsonb_array_elements(coalesce(w->'deferral_schedules', '[]'::jsonb)) x) THEN
    RAISE EXCEPTION 'onboarding execute: deferral schedules (% totalling %) do not equal the plan', n, v USING ERRCODE = 'check_violation';
  END IF;
  SELECT count(*) INTO n FROM conversion_reconciling_items WHERE batch_id = p_batch AND status = 'open';
  IF n <> n_items THEN RAISE EXCEPTION 'onboarding execute: % reconciling items recorded, % planned', n, n_items USING ERRCODE = 'check_violation'; END IF;

  SELECT count(*), coalesce(sum(total_debits_cents), 0) INTO n_post, v FROM journal_entries
   WHERE community_id = comm AND posting_date >= cutover AND left(reference, length(code)) <> code
     AND (status = 'posted' OR (status = 'voided' AND void_reversal_je_id IS NOT NULL));
  IF n_post <> (pre->'post_cutover_entries'->>'count')::bigint OR v <> (pre->'post_cutover_entries'->>'debits_cents')::bigint THEN
    RAISE EXCEPTION 'onboarding execute: post-cutover entries changed during execute' USING ERRCODE = 'check_violation';
  END IF;
  SELECT count(*) INTO n FROM journal_entries WHERE community_id = comm AND left(reference, length(code)) = code;
  IF n <> n_open + n_neut + n_repost THEN RAISE EXCEPTION 'onboarding execute: % conversion entries written, % planned', n, n_open + n_neut + n_repost USING ERRCODE = 'check_violation'; END IF;
  counts := jsonb_build_object('opening_journal_entries', n_open, 'neutralize_journal_entries', n_neut, 'repost_journal_entries', n_repost,
                               'supersede_journal_entries', n_sup, 'revert_ar_batches', n_rev, 'ar_opening_rows', n_ar, 'ap_opening_invoices', n_ap);
  IF counts IS DISTINCT FROM (SELECT jsonb_build_object('opening_journal_entries', (s->>'opening_journal_entries')::int, 'neutralize_journal_entries', (s->>'neutralize_journal_entries')::int,
        'repost_journal_entries', (s->>'repost_journal_entries')::int, 'supersede_journal_entries', (s->>'supersede_journal_entries')::int, 'revert_ar_batches', (s->>'revert_ar_batches')::int,
        'ar_opening_rows', (s->>'ar_opening_rows')::int, 'ap_opening_invoices', (s->>'ap_opening_invoices')::int) FROM (SELECT plan->'summary' AS s) q) THEN
    RAISE EXCEPTION 'onboarding execute: write counts % do not equal the plan', counts USING ERRCODE = 'check_violation';
  END IF;
  -- 501: the builder counts (a plan without a builder section has none of these keys and writes none of these rows).
  IF (plan->'summary') ? 'builder_coverage_rows' OR n_bcov + n_brow + n_sched + n_items > 0 THEN
    IF jsonb_build_object('builder_coverage_rows', n_bcov, 'builder_ledger_rows', n_brow, 'deferral_schedules', n_sched, 'reconciling_items', n_items)
       IS DISTINCT FROM (SELECT jsonb_build_object('builder_coverage_rows', coalesce((s->>'builder_coverage_rows')::int, 0), 'builder_ledger_rows', coalesce((s->>'builder_ledger_rows')::int, 0),
                                 'deferral_schedules', coalesce((s->>'deferral_schedules')::int, 0), 'reconciling_items', coalesce((s->>'reconciling_items')::int, 0)) FROM (SELECT plan->'summary' AS s) q) THEN
      RAISE EXCEPTION 'onboarding execute: builder write counts (% coverage, % ledger, % schedules, % items) do not equal the plan', n_bcov, n_brow, n_sched, n_items USING ERRCODE = 'check_violation';
    END IF;
    counts := counts || jsonb_build_object('builder_coverage_rows', n_bcov, 'builder_ledger_rows', n_brow, 'deferral_schedules', n_sched, 'reconciling_items', n_items);
  END IF;
  proof := jsonb_build_object('cutoff_trial_balance', 'equal', 'current_trial_balance', 'equal', 'ar_receivable_cents', ar_recv, 'ar_current_owner_prepaid_cents', ar_cur,
                              'ar_prior_owner_credit_cents', ar_prior, 'post_cutover_entries_unchanged', n_post, 'cutover_date', cutover, 'write_counts', counts)
           || CASE WHEN bb IS NOT NULL THEN jsonb_build_object('builder_ledger_cents', b_ledger, 'builder_coverage_rows', n_bcov) ELSE '{}'::jsonb END;
  controls := jsonb_build_array(
    jsonb_build_object('code', 'execute.preconditions_held', 'label', 'Every recorded precondition held against live data at execute time', 'status', 'PASS', 'level', 'execute'),
    jsonb_build_object('code', 'execute.cutoff_tb_equals_source', 'label', 'Trusted TB at the cutoff equals the source TB on every account', 'status', 'PASS', 'level', 'execute'),
    jsonb_build_object('code', 'execute.current_tb_equals_projection', 'label', 'Trusted TB through today equals the projected TB', 'status', 'PASS', 'level', 'execute'),
    jsonb_build_object('code', 'execute.homeowner_ledger_equals_plan', 'label', 'Homeowner ledger receivables / prepaids / prior-owner credits equal the plan', 'status', 'PASS', 'level', 'execute',
                       'left_cents', ar_recv, 'right_cents', (ab->>'receivable_cents')::bigint, 'difference_cents', 0),
    jsonb_build_object('code', 'execute.post_cutover_unchanged', 'label', 'Every post-cutover entry is unchanged', 'status', 'PASS', 'level', 'execute'),
    jsonb_build_object('code', 'execute.write_counts_equal_plan', 'label', 'Exactly the planned rows were written', 'status', 'PASS', 'level', 'execute'))
    || CASE WHEN bb IS NOT NULL THEN jsonb_build_array(
         jsonb_build_object('code', 'execute.builder_coverage_equals_plan', 'label', 'Builder ledger = the plan = the builder entry''s AR lines; every resolved builder lot has its posted conversion coverage', 'status', 'PASS', 'level', 'execute',
                            'left_cents', b_ledger, 'right_cents', (bb->>'ledger_cents')::bigint, 'difference_cents', 0))
       ELSE '[]'::jsonb END;

  -- ------------------------------------- execute result, batch posted, lock closed
  done := onboarding_record_completion(p_batch, 'execute', 'PASS', '[]'::jsonb, controls,
            jsonb_build_object('execution_id', exec_id, 'preflight_completion_id', c.id, 'preflight_sha256', p_preflight_sha256, 'write_counts', counts, 'proof', proof),
            p_actor_kind, p_actor_id);
  UPDATE conversion_batches SET status = 'posted', write_locked = TRUE,
         notes = coalesce(notes || ' ', '') || 'posted by ' || prov WHERE id = p_batch;
  INSERT INTO onboarding_execution_writes (execution_id, batch_id, table_name, row_id, action, write_kind, write_key, before, after)
  VALUES (exec_id, p_batch, 'conversion_batches', p_batch, 'update', 'conversion_batch', code, jsonb_build_object('status', bt.status), jsonb_build_object('status', 'posted'));
  INSERT INTO onboarding_executions (id, batch_id, community_id, status, preflight_completion_id, preflight_sha256, approval_event_id, advance_event_id, execute_completion_id,
                                     actor_kind, actor_id, write_counts, proof, proof_plan)
  VALUES (exec_id, p_batch, comm, 'committed', c.id, p_preflight_sha256, appr, adv, done, p_actor_kind, p_actor_id, counts, proof, coalesce(proof_plan, '[]'::jsonb));
  RETURN jsonb_build_object('status', 'executed', 'execution_id', exec_id, 'execute_completion_id', done, 'write_counts', counts, 'proof', proof,
                            'rows_written_now', (SELECT count(*) FROM onboarding_execution_writes WHERE execution_id = exec_id));
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 4) Builder accrual (generic: everything from the community's program)
-- ---------------------------------------------------------------------------
-- The one configured builder every owner on this tenure is; NULL when it is not
-- a builder tenure. 'matched' < 'owners' tells a lot whose owners mix a builder
-- with others.
CREATE OR REPLACE FUNCTION builder_tenure_match(p_tenure_id uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  WITH t AS (SELECT * FROM ownership_tenures WHERE id = p_tenure_id),
  owners AS (
    SELECT c.full_name,
           (SELECT array_agg(DISTINCT tb.builder_company_id)
              FROM transfer_proration_builders tb JOIN builder_companies bc ON bc.id = tb.builder_company_id, t
             WHERE tb.community_id = t.community_id AND tb.active AND transfer_proration_name_has(c.full_name, bc.company_name)) AS hits
      FROM property_ownerships po JOIN contacts c ON c.id = po.contact_id
     WHERE po.tenure_id = p_tenure_id)
  SELECT jsonb_build_object('owners', count(*), 'matched', count(*) FILTER (WHERE hits IS NOT NULL),
           'builders', (SELECT coalesce(jsonb_agg(DISTINCT x), '[]'::jsonb) FROM owners o2, unnest(o2.hits) x),
           'builder_company_id', CASE WHEN count(*) > 0 AND count(*) = count(*) FILTER (WHERE hits IS NOT NULL)
                                       AND (SELECT count(DISTINCT x) FROM owners o2, unnest(o2.hits) x) = 1
                                      THEN (SELECT min(x::text) FROM owners o2, unnest(o2.hits) x)::uuid END)
    FROM owners
$fn$;
REVOKE ALL ON FUNCTION builder_tenure_match(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION builder_tenure_match(uuid) TO service_role;

-- The end of every billing period of an assessment year, by the program's
-- cadence (1, 3, 6 or 12 months from the year's first day; the last ends on the
-- year's last day).
CREATE OR REPLACE FUNCTION builder_cadence_ends(p_year_start date, p_year_end date, p_cadence_months int)
RETURNS SETOF date LANGUAGE sql IMMUTABLE AS $fn$
  SELECT least((p_year_start + make_interval(months => k * p_cadence_months) - interval '1 day')::date, p_year_end)
    FROM generate_series(1, (12 / p_cadence_months)) k
$fn$;

-- The explicit post-conversion activation of the periodic accrual (who, when).
-- Refused until the community's accounting conversion is posted (the program
-- guard enforces it for any write).
CREATE OR REPLACE FUNCTION activate_builder_accrual(p_community_id uuid, p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE p builder_assessment_programs%ROWTYPE;
BEGIN
  IF coalesce(btrim(p_actor), '') = '' THEN RAISE EXCEPTION 'actor required'; END IF;
  SELECT * INTO p FROM builder_assessment_programs WHERE community_id = p_community_id FOR UPDATE;
  IF NOT FOUND OR NOT p.active THEN RAISE EXCEPTION 'no active builder assessment program for this community'; END IF;
  IF p.accrual_activated_at IS NOT NULL THEN
    RETURN jsonb_build_object('status', 'already_active', 'activated_at', p.accrual_activated_at, 'activated_by', p.accrual_activated_by);
  END IF;
  UPDATE builder_assessment_programs SET accrual_activated_at = now(), accrual_activated_by = btrim(p_actor) WHERE community_id = p_community_id
  RETURNING * INTO p;
  RETURN jsonb_build_object('status', 'activated', 'activated_at', p.accrual_activated_at, 'activated_by', p.accrual_activated_by);
END;
$fn$;
REVOKE ALL ON FUNCTION activate_builder_accrual(uuid, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION activate_builder_accrual(uuid, text) TO service_role;

-- What the accrual through p_through would bill: every COMPLETED billing period
-- (period end <= p_through) after each builder lot's last covered day. Read-only.
CREATE OR REPLACE FUNCTION builder_accrual_plan(p_community_id uuid, p_through date)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
  prog builder_assessment_programs%ROWTYPE; ho community_assessment_rates%ROWTYPE;
  conv_code text; conv_asof date; t record; m jsonb; cov jsonb; yb record; st date; pe date; ps date; mf date;
  pct numeric; annual bigint; base bigint; tu bigint; prior_sum bigint; prior_from date; mixed boolean;
  lots jsonb := '[]'::jsonb; blocked jsonb := '[]'::jsonb; periods jsonb; why text; total bigint := 0; n_per int := 0; guard int;
BEGIN
  IF p_through IS NULL THEN RAISE EXCEPTION 'the accrual needs a through date'; END IF;
  SELECT * INTO prog FROM builder_assessment_programs WHERE community_id = p_community_id AND active;
  IF NOT FOUND OR NOT EXISTS (SELECT 1 FROM transfer_proration_builders WHERE community_id = p_community_id AND active) THEN
    RETURN jsonb_build_object('applies', false, 'reason', 'community_not_configured');
  END IF;
  SELECT batch_code, as_of_date INTO conv_code, conv_asof FROM conversion_batches
   WHERE community_id = p_community_id AND status = 'posted' ORDER BY as_of_date DESC, created_at DESC LIMIT 1;
  IF conv_code IS NULL THEN RETURN jsonb_build_object('applies', true, 'converted', false, 'activated', false, 'reason', 'not_converted', 'lots', '[]'::jsonb, 'blocked', '[]'::jsonb); END IF;
  SELECT * INTO ho FROM community_assessment_rates WHERE community_id = p_community_id AND owner_class = 'homeowner';
  IF ho.id IS NULL OR ho.annual_amount_cents IS NULL THEN RETURN jsonb_build_object('applies', true, 'converted', true, 'reason', 'rates_missing', 'lots', '[]'::jsonb, 'blocked', '[]'::jsonb); END IF;
  annual := ho.annual_amount_cents; pct := prog.builder_rate_pct;

  FOR t IN SELECT ot.*, p.street_address, p.trusted_account_number, p.vantaca_account_id AS p_vacct
             FROM ownership_tenures ot JOIN properties p ON p.id = ot.property_id
            WHERE ot.community_id = p_community_id AND ot.kind = 'owner' AND ot.end_date IS NULL
            ORDER BY p.street_address, ot.id LOOP
    m := builder_tenure_match(t.id);
    IF (m->>'matched')::int = 0 THEN CONTINUE; END IF;
    IF m->>'builder_company_id' IS NULL THEN
      blocked := blocked || jsonb_build_object('property_id', t.property_id, 'street_address', t.street_address, 'tenure_id', t.id, 'reason', 'owners_mixed_or_multiple_builders');
      CONTINUE;
    END IF;
    periods := '[]'::jsonb; why := NULL; cov := NULL;
    SELECT * INTO yb FROM assessment_year_bounds(ho.fiscal_year_end_mmdd, conv_asof);
    guard := 0;
    WHILE yb.year_start <= p_through AND guard < 50 LOOP
      guard := guard + 1;
      cov := builder_coverage(t.id, yb.year_start);
      IF (cov->>'count')::int = 0 THEN
        IF conv_asof BETWEEN yb.year_start AND yb.year_end AND NOT (t.origin = 'transfer' AND t.start_date > conv_asof) THEN why := 'builder_coverage_missing'; EXIT; END IF;
        st := builder_coverage_start(t.id, yb.year_start);
      ELSE
        IF NOT (cov->>'valid')::boolean THEN why := 'builder_coverage_invalid'; EXIT; END IF;
        IF (cov->>'pending')::int > 0 THEN why := 'builder_coverage_pending'; EXIT; END IF;
        st := (cov->>'covered_through')::date + 1;
      END IF;
      SELECT coalesce(sum(amount_cents), 0), min(covered_from),
             coalesce(bool_or(annual_assessment_cents <> annual OR builder_rate_pct <> pct), false)
        INTO prior_sum, prior_from, mixed
        FROM builder_assessment_coverage WHERE tenure_id = t.id AND year_start = yb.year_start AND status <> 'voided';
      prior_from := coalesce(prior_from, st);
      ps := yb.year_start;
      FOR pe IN SELECT * FROM builder_cadence_ends(yb.year_start, yb.year_end, prog.accrual_cadence_months) LOOP
        IF pe > p_through THEN EXIT; END IF;
        IF pe >= st THEN
          mf := greatest(ps, st);
          base := round(annual::numeric * pct * (pe - mf + 1) / (100 * yb.days_in_year));
          tu := 0;
          IF pe = yb.year_end AND prior_from = yb.year_start AND NOT mixed THEN
            tu := round(annual::numeric * pct / 100) - prior_sum - base;
          END IF;
          periods := periods || jsonb_build_object('fiscal_year', yb.fiscal_year, 'year_start', yb.year_start, 'year_end', yb.year_end,
            'covered_from', mf, 'covered_through', pe, 'days', pe - mf + 1, 'days_in_year', yb.days_in_year,
            'annual_assessment_cents', annual, 'builder_rate_pct', pct, 'base_amount_cents', base, 'rounding_true_up_cents', tu, 'amount_cents', base + tu);
          prior_sum := prior_sum + base + tu; total := total + base + tu; n_per := n_per + 1;
        END IF;
        ps := pe + 1;
      END LOOP;
      SELECT * INTO yb FROM assessment_year_bounds(ho.fiscal_year_end_mmdd, yb.year_end + 1);
    END LOOP;
    IF why IS NOT NULL THEN
      blocked := blocked || jsonb_build_object('property_id', t.property_id, 'street_address', t.street_address, 'tenure_id', t.id, 'reason', why, 'coverage', cov);
    ELSIF jsonb_array_length(periods) > 0 THEN
      lots := lots || jsonb_build_object('property_id', t.property_id, 'street_address', t.street_address, 'tenure_id', t.id,
        'account_number', t.trusted_account_number, 'vantaca_account_id', coalesce(t.vantaca_account_id, t.p_vacct),
        'builder_company_id', m->>'builder_company_id', 'periods', periods);
    END IF;
  END LOOP;
  RETURN jsonb_build_object('applies', true, 'converted', true, 'activated', prog.accrual_activated_at IS NOT NULL,
    'activated_at', prog.accrual_activated_at, 'activated_by', prog.accrual_activated_by,
    'conversion_code', conv_code, 'conversion_as_of', conv_asof, 'through', p_through, 'cadence_months', prog.accrual_cadence_months,
    'ar_account_number', prog.ar_account_number, 'income_account_number', prog.income_account_number,
    'rate', jsonb_build_object('annual_cents', annual, 'builder_rate_pct', pct, 'year_end_mmdd', ho.fiscal_year_end_mmdd, 'homeowner_rate_id', ho.id),
    'lots', lots, 'blocked', blocked, 'periods', n_per, 'total_cents', total);
END;
$fn$;
REVOKE ALL ON FUNCTION builder_accrual_plan(uuid, date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION builder_accrual_plan(uuid, date) TO service_role;

-- Stage the accrual: a draft batch, its ledger rows (dated each period's last
-- day, tenure-stamped) and pending coverage. Refused until the program's accrual
-- is activated, and for a through date that has not passed yet (a period is billed
-- only after it ends; p_as_of defaults to today). An unfinished run is returned,
-- never doubled.
CREATE OR REPLACE FUNCTION builder_accrual_stage(p_community_id uuid, p_through date, p_actor text, p_as_of date DEFAULT current_date)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE plan jsonb; run builder_accrual_runs%ROWTYPE; lot jsonb; per jsonb; b_id uuid; txn uuid; idx int := 0; mc uuid; n_rows int;
BEGIN
  IF coalesce(btrim(p_actor), '') = '' THEN RAISE EXCEPTION 'actor required'; END IF;
  IF p_through IS NULL OR p_through >= coalesce(p_as_of, current_date) THEN
    RAISE EXCEPTION 'the accrual bills only periods that have ended: % is not before %', p_through, coalesce(p_as_of, current_date);
  END IF;
  SELECT * INTO run FROM builder_accrual_runs WHERE community_id = p_community_id AND status = 'staged' FOR UPDATE;
  IF FOUND THEN RETURN builder_accrual_run_view(run.id) || jsonb_build_object('resumed', true); END IF;
  plan := builder_accrual_plan(p_community_id, p_through);
  IF coalesce((plan->>'converted')::boolean, false) AND NOT coalesce((plan->>'activated')::boolean, false) THEN
    RAISE EXCEPTION 'the builder accrual is not activated for this community (activate it after the conversion is posted)';
  END IF;
  IF NOT coalesce((plan->>'applies')::boolean, false) OR NOT coalesce((plan->>'converted')::boolean, false) OR coalesce((plan->>'periods')::int, 0) = 0 THEN
    RETURN jsonb_build_object('status', 'nothing_to_accrue', 'plan', plan);
  END IF;
  SELECT management_company_id INTO mc FROM communities WHERE id = p_community_id;
  SELECT sum(jsonb_array_length(l->'periods')) INTO n_rows FROM jsonb_array_elements(plan->'lots') l;
  INSERT INTO transaction_upload_batches (management_company_id, community_id, period_label, as_of_date, source_format, status, row_count, account_count,
      total_charges_cents, total_payments_cents, min_transaction_date, max_transaction_date, uploaded_by, notes)
  VALUES (mc, p_community_id, 'Builder assessment accrual through ' || p_through, p_through, 'manual', 'draft', n_rows, jsonb_array_length(plan->'lots'),
      (plan->>'total_cents')::bigint, 0,
      (SELECT min((p->>'covered_through')::date) FROM jsonb_array_elements(plan->'lots') l, jsonb_array_elements(l->'periods') p),
      (SELECT max((p->>'covered_through')::date) FROM jsonb_array_elements(plan->'lots') l, jsonb_array_elements(l->'periods') p),
      'builder_accrual', format('Builder assessment accrual through %s; staged by %s', p_through, p_actor))
  RETURNING id INTO b_id;
  INSERT INTO builder_accrual_runs (community_id, through_date, status, batch_id, plan, created_by)
  VALUES (p_community_id, p_through, 'staged', b_id, plan, p_actor) RETURNING * INTO run;
  FOR lot IN SELECT x FROM jsonb_array_elements(plan->'lots') x LOOP
    FOR per IN SELECT x FROM jsonb_array_elements(lot->'periods') x LOOP
      idx := idx + 1;
      INSERT INTO homeowner_transactions (source_batch_id, source_row_index, community_id, vantaca_account_id, trusted_account_number, property_id, tenure_id,
          transaction_date, description, txn_type, charge_category, amount_cents, raw_row_jsonb)
      VALUES (b_id, idx, p_community_id, lot->>'vantaca_account_id', lot->>'account_number', (lot->>'property_id')::uuid, (lot->>'tenure_id')::uuid,
          (per->>'covered_through')::date,
          format('Builder assessment %s to %s: %s/%s days at %s%% of $%s%s', per->>'covered_from', per->>'covered_through', per->>'days', per->>'days_in_year',
                 per->>'builder_rate_pct', to_char((per->>'annual_assessment_cents')::numeric / 100, 'FM999999990.00'),
                 CASE WHEN (per->>'rounding_true_up_cents')::bigint <> 0 THEN format(' (includes year-end rounding true-up %s cents)', per->>'rounding_true_up_cents') ELSE '' END),
          'charge', 'assessment', (per->>'amount_cents')::bigint,
          jsonb_build_object('source', 'builder_accrual', 'accrual_run_id', run.id, 'period', per))
      RETURNING id INTO txn;
      INSERT INTO builder_assessment_coverage (community_id, property_id, account_number, vantaca_account_id, tenure_id, builder_company_id, fiscal_year, year_start, year_end,
          covered_from, covered_through, days, days_in_year, annual_assessment_cents, builder_rate_pct, rate_source, base_amount_cents, rounding_true_up_cents,
          amount_cents, source_type, accrual_run_id, batch_id, homeowner_txn_id, status, created_by)
      VALUES (p_community_id, (lot->>'property_id')::uuid, lot->>'account_number', lot->>'vantaca_account_id', (lot->>'tenure_id')::uuid, (lot->>'builder_company_id')::uuid,
          (per->>'fiscal_year')::int, (per->>'year_start')::date, (per->>'year_end')::date, (per->>'covered_from')::date, (per->>'covered_through')::date,
          (per->>'days')::int, (per->>'days_in_year')::int,
          (per->>'annual_assessment_cents')::bigint, (per->>'builder_rate_pct')::numeric,
          jsonb_build_object('annual', 'community_assessment_rates', 'rate', 'builder_assessment_programs') || coalesce(plan->'rate', '{}'::jsonb),
          (per->>'base_amount_cents')::bigint, (per->>'rounding_true_up_cents')::bigint, (per->>'amount_cents')::bigint,
          'scheduled_accrual', run.id, b_id, txn, 'pending', 'accrual:' || p_actor);
    END LOOP;
  END LOOP;
  RETURN builder_accrual_run_view(run.id) || jsonb_build_object('resumed', false);
END;
$fn$;

-- A run, grouped by billing period end: what each period's journal entry must equal.
CREATE OR REPLACE FUNCTION builder_accrual_run_view(p_run uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $fn$
  SELECT jsonb_build_object('status', r.status, 'run_id', r.id, 'community_id', r.community_id, 'through', r.through_date, 'batch_id', r.batch_id,
    'ar_account_number', r.plan->>'ar_account_number', 'income_account_number', r.plan->>'income_account_number', 'blocked', coalesce(r.plan->'blocked', '[]'::jsonb),
    'periods', coalesce((SELECT jsonb_agg(jsonb_build_object('period_end', pe, 'amount_cents', amt, 'lots', n, 'pending', pend, 'journal_entry_reference', ref,
                                'lines', lines) ORDER BY pe)
       FROM (SELECT c.covered_through AS pe, sum(c.amount_cents) AS amt, count(*) AS n,
                    count(*) FILTER (WHERE c.status = 'pending') AS pend, max(c.journal_entry_reference) AS ref,
                    jsonb_agg(jsonb_build_object('property_id', c.property_id, 'amount_cents', c.amount_cents, 'from', c.covered_from, 'through', c.covered_through,
                                                 'rounding_true_up_cents', c.rounding_true_up_cents) ORDER BY c.covered_from, c.property_id) AS lines
               FROM builder_assessment_coverage c WHERE c.accrual_run_id = r.id AND c.status <> 'voided'
              GROUP BY 1) g), '[]'::jsonb))
    FROM builder_accrual_runs r WHERE r.id = p_run
$fn$;

-- One period's journal entry is posted: it must be this community's, posted, and
-- its receivable lines (the ones naming a lot) must equal the period's coverage
-- exactly. Marks the period posted; when nothing in the run is pending, commits
-- the batch and closes the run.
CREATE OR REPLACE FUNCTION builder_accrual_finish(p_run uuid, p_period_end date, p_je uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $fn$
DECLARE run builder_accrual_runs%ROWTYPE; j journal_entries%ROWTYPE; want bigint; got bigint; n int;
BEGIN
  SELECT * INTO run FROM builder_accrual_runs WHERE id = p_run FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'accrual run % not found', p_run; END IF;
  SELECT * INTO j FROM journal_entries WHERE id = p_je;
  IF NOT FOUND OR j.community_id <> run.community_id OR j.status <> 'posted' THEN RAISE EXCEPTION 'journal entry % is not a posted entry of this community', p_je; END IF;
  SELECT coalesce(sum(amount_cents), 0), count(*) INTO want, n FROM builder_assessment_coverage
   WHERE accrual_run_id = p_run AND status = 'pending' AND covered_through = p_period_end;
  IF n > 0 THEN
    SELECT coalesce(sum(jl.debit_cents - jl.credit_cents), 0) INTO got FROM journal_entry_lines jl
     WHERE jl.journal_entry_id = p_je AND jl.property_id IS NOT NULL;
    IF got <> want THEN RAISE EXCEPTION 'journal entry % debits AR %, the period''s coverage is %', j.reference, got, want; END IF;
    UPDATE builder_assessment_coverage SET status = 'posted', journal_entry_id = p_je, journal_entry_reference = j.reference
     WHERE accrual_run_id = p_run AND status = 'pending' AND covered_through = p_period_end;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM builder_assessment_coverage WHERE accrual_run_id = p_run AND status = 'pending') AND run.status = 'staged' THEN
    UPDATE transaction_upload_batches SET status = 'committed', committed_at = now() WHERE id = run.batch_id AND status = 'draft';
    UPDATE builder_accrual_runs SET status = 'posted', posted_at = now() WHERE id = p_run;
  END IF;
  RETURN builder_accrual_run_view(p_run);
END;
$fn$;
REVOKE ALL ON FUNCTION builder_accrual_stage(uuid, date, text, date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION builder_accrual_run_view(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION builder_accrual_finish(uuid, date, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION builder_accrual_stage(uuid, date, text, date) TO service_role;
GRANT EXECUTE ON FUNCTION builder_accrual_run_view(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION builder_accrual_finish(uuid, date, uuid) TO service_role;

-- ---------------------------------------------------------------------------
-- 5) Coverage status: one function for the AR email, Home Sales and the warning
-- ---------------------------------------------------------------------------
-- expected_through: the latest billing-period end at least 5 days before
-- p_as_of (the program's cadence), never before the conversion as-of. RED when a
-- lot is blocked, or is not covered through the last assessment-year end that is
-- at least 5 days past; AMBER when simply behind or when the accrual has not been
-- activated since the conversion. Open reconciling items are listed with it.
CREATE OR REPLACE FUNCTION builder_coverage_status(p_community_id uuid, p_as_of date)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $fn$
DECLARE
  prog builder_assessment_programs%ROWTYPE; ho community_assessment_rates%ROWTYPE;
  conv_code text; conv_asof date; expect date; ye_last date; yb record; t record; m jsonb; cov jsonb; thru date; sev text; why text;
  lots jsonb := '[]'::jsonb; red int := 0; amber int := 0; ok int := 0; items jsonb; staged jsonb;
BEGIN
  SELECT * INTO prog FROM builder_assessment_programs WHERE community_id = p_community_id AND active;
  IF NOT FOUND OR NOT EXISTS (SELECT 1 FROM transfer_proration_builders WHERE community_id = p_community_id AND active) THEN
    RETURN jsonb_build_object('applies', false);
  END IF;
  SELECT batch_code, as_of_date INTO conv_code, conv_asof FROM conversion_batches
   WHERE community_id = p_community_id AND status = 'posted' ORDER BY as_of_date DESC, created_at DESC LIMIT 1;
  SELECT coalesce(jsonb_agg(jsonb_build_object('id', i.id, 'kind', i.kind, 'item_key', i.item_key, 'account_number', i.account_number, 'property_id', i.property_id,
           'amount_cents', i.amount_cents, 'detail', i.detail, 'created_at', i.created_at) ORDER BY i.created_at), '[]'::jsonb)
    INTO items FROM conversion_reconciling_items i WHERE i.community_id = p_community_id AND i.status = 'open';
  IF conv_code IS NULL THEN RETURN jsonb_build_object('applies', true, 'converted', false, 'open_reconciling_items', items); END IF;
  SELECT * INTO ho FROM community_assessment_rates WHERE community_id = p_community_id AND owner_class = 'homeowner';
  IF ho.id IS NULL THEN RETURN jsonb_build_object('applies', true, 'converted', true, 'status', 'red', 'reason', 'rates_missing', 'open_reconciling_items', items); END IF;
  -- the latest period end (any assessment year) at least 5 days before p_as_of
  SELECT * INTO yb FROM assessment_year_bounds(ho.fiscal_year_end_mmdd, p_as_of - 5);
  SELECT max(e) INTO expect FROM (
    SELECT builder_cadence_ends(yb.year_start, yb.year_end, prog.accrual_cadence_months) AS e
    UNION ALL SELECT yb.year_start - 1) x WHERE e <= p_as_of - 5;
  expect := greatest(expect, conv_asof);
  ye_last := CASE WHEN yb.year_end <= p_as_of - 5 THEN yb.year_end ELSE yb.year_start - 1 END;   -- the last assessment-year end at least 5 days past
  SELECT to_jsonb(r) INTO staged FROM (SELECT id, through_date, created_at FROM builder_accrual_runs WHERE community_id = p_community_id AND status = 'staged') r;
  FOR t IN SELECT ot.*, p.street_address, p.trusted_account_number FROM ownership_tenures ot JOIN properties p ON p.id = ot.property_id
            WHERE ot.community_id = p_community_id AND ot.kind = 'owner' AND ot.end_date IS NULL ORDER BY p.street_address, ot.id LOOP
    m := builder_tenure_match(t.id);
    IF (m->>'matched')::int = 0 THEN CONTINUE; END IF;
    SELECT max(covered_through) INTO thru FROM builder_assessment_coverage WHERE tenure_id = t.id AND status <> 'voided';
    cov := builder_coverage(t.id, (SELECT year_start FROM assessment_year_bounds(ho.fiscal_year_end_mmdd, coalesce(thru, conv_asof))));
    why := NULL; sev := 'ok';
    IF m->>'builder_company_id' IS NULL THEN why := 'owners_mixed_or_multiple_builders'; sev := 'red';
    ELSIF NOT (cov->>'valid')::boolean THEN why := 'coverage_invalid'; sev := 'red';
    ELSIF (cov->>'pending')::int > 0 THEN why := 'coverage_pending'; sev := 'red';
    ELSIF thru IS NULL AND NOT (t.origin = 'transfer' AND t.start_date > conv_asof) THEN why := 'coverage_missing'; sev := 'red';
    ELSIF coalesce(thru, t.start_date - 1) < expect THEN
      why := 'behind';
      sev := CASE WHEN ye_last > conv_asof AND coalesce(thru, '1900-01-01'::date) < ye_last THEN 'red' ELSE 'amber' END;
    END IF;
    IF sev = 'red' THEN red := red + 1; ELSIF sev = 'amber' THEN amber := amber + 1; ELSE ok := ok + 1; END IF;
    lots := lots || jsonb_build_object('property_id', t.property_id, 'street_address', t.street_address, 'account_number', t.trusted_account_number, 'tenure_id', t.id,
      'covered_through', thru, 'expected_through', expect, 'severity', sev, 'reason', why);
  END LOOP;
  RETURN jsonb_build_object('applies', true, 'converted', true, 'conversion_code', conv_code, 'conversion_as_of', conv_asof, 'as_of', p_as_of,
    'expected_through', expect, 'cadence_months', prog.accrual_cadence_months,
    'accrual_active', prog.accrual_activated_at IS NOT NULL, 'accrual_activated_at', prog.accrual_activated_at, 'accrual_activated_by', prog.accrual_activated_by,
    'lots', lots, 'counts', jsonb_build_object('ok', ok, 'amber', amber, 'red', red, 'lots', ok + amber + red),
    'covered_through_min', (SELECT min((x->>'covered_through')::date) FROM jsonb_array_elements(lots) x),
    'staged_run', staged, 'open_reconciling_items', items,
    'status', CASE WHEN red > 0 OR staged IS NOT NULL THEN 'red'
                   WHEN amber > 0 OR jsonb_array_length(items) > 0 OR prog.accrual_activated_at IS NULL THEN 'amber' ELSE 'ok' END);
END;
$fn$;
REVOKE ALL ON FUNCTION builder_coverage_status(uuid, date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION builder_coverage_status(uuid, date) TO service_role;

COMMIT;
