#!/usr/bin/env node
// ============================================================================
// scripts/build_tx_icons.js  (Issue #6, 2026-09-29)
// ----------------------------------------------------------------------------
// Generates public/app/tx-icons.js — the Trusted product icon set — from the
// lucide-static package (ISC). Only the curated names below ship to the
// browser, so the page never loads the full 2,000-icon library.
//
// To add an icon: add its Lucide name to ICONS (key = our name, value = the
// Lucide file name), run `node scripts/build_tx_icons.js`, commit the output.
// lucide-static is a devDependency; production never needs it at runtime.
// ============================================================================
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const OUT = path.join(__dirname, '..', 'public', 'app', 'tx-icons.js');

const ICONS = {
  today: 'calendar-days',
  communities: 'building-2',
  owners: 'users',
  financial: 'landmark',
  operations: 'list-checks',
  projects: 'hammer',
  governance: 'scale',
  team: 'user-round',
  bell: 'bell',
  chevronDown: 'chevron-down',
  arrowRight: 'arrow-right',
  check: 'check',
  circle: 'circle',
  sparkles: 'sparkles',
  search: 'search',
  mail: 'mail',
  receipt: 'receipt',
  inbox: 'inbox',
  alert: 'triangle-alert',
  refresh: 'refresh-cw',
  menu: 'menu',
  info: 'info',
};

const version = require(path.join(SRC, '..', 'package.json')).version;
const out = {};
for (const [name, file] of Object.entries(ICONS)) {
  const svg = fs.readFileSync(path.join(SRC, file + '.svg'), 'utf8');
  // Keep only the drawing elements; the wrapper <svg> is rebuilt at render
  // time so size, colour and stroke width come from the caller.
  const inner = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*/, '')
    .replace(/\s+/g, ' ').replace(/> </g, '><').trim();
  if (!inner) throw new Error('empty icon: ' + file);
  out[name] = inner;
}

const body = `// GENERATED by scripts/build_tx_icons.js from lucide-static v${version} (ISC).
// Do not edit by hand — add the name to ICONS in the script and re-run it.
(function (root) {
  var PATHS = ${JSON.stringify(out, null, 2)};
  function icon(name, opts) {
    opts = opts || {};
    var d = PATHS[name];
    if (!d) { console.warn('[tx-icons] unknown icon', name); return ''; }
    var s = opts.size || 18;
    return '<svg class="tx-icon" width="' + s + '" height="' + s + '" viewBox="0 0 24 24" fill="none" stroke="' +
      (opts.color || 'currentColor') + '" stroke-width="' + (opts.stroke || 1.75) +
      '" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + d + '</svg>';
  }
  var api = { icon: icon, names: Object.keys(PATHS) };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.TXIcons = api;
})(typeof window !== 'undefined' ? window : this);
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log('wrote', path.relative(process.cwd(), OUT), Object.keys(out).length, 'icons');
