#!/usr/bin/env node
// ============================================================================
// scripts/seed_platform_knowledge.js  (Ed 2026-07-07)
// ----------------------------------------------------------------------------
// The platform's self-knowledge: what trustEd does, where each screen lives,
// how to use it. askEd + Claire retrieve these from the `playbook` (semantic),
// so "where is X / how do I do Y" gets the REAL answer instead of a
// hallucinated one (the Laurie/Homeowner-360 incident).
//
// DISCIPLINE (see CLAUDE.md): when you ship or move a feature, add/update its
// entry here and re-run this script. A feature isn't "done" until the platform
// can explain it. Idempotent — deletes the prior platform_feature set and
// re-inserts, so this file is the single source of truth.
//
//   node -r dotenv/config scripts/seed_platform_knowledge.js
// ============================================================================
const { createClient } = require('@supabase/supabase-js');
const OpenAI = require('openai');
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// Each: what a staffer might ASK (situation, drives semantic match) → the real
// answer (response). Keep responses accurate; if unsure of an exact click-path,
// describe WHAT it does rather than invent a menu.
const FEATURES = [
  {
    situation: 'Which communities are fully imported from Vantaca, what data is missing or not reconciled for a community, where is data readiness or import status, or what still needs to come over?',
    response: 'Open Communities in the new Trusted design (address /app/communities; the Today preview links to it from the sidebar). It lists every Bedrock community with a row of twelve status dots and the areas that need action, worst first. Prospects and communities leaving Bedrock (for example Eaglewood) are listed separately as not being imported. Click a community (/app/communities/<id>) to see each data area: community profile, properties and owners, owner ledger conversion, receivables vs GL, general ledger, budget, bank reconciliation, violations history, vendors, documents, board and contacts, and insurance. Each area says what the data shows, what is missing, the next step, and the table it was read from, with a button to the screen where the work is done. Statuses: Error (a check failed or the data could not be read), Partial, Not reconciled (imported but the proving check has not passed or cannot run yet, such as receivables before the ledger conversion is posted), In progress, Not imported, Not verified (imported but there is no source total to prove it is complete, such as violations or vendors), Ready (proven by a stored check, such as a posted ledger conversion or an exact receivables tie to the GL), and Not applicable. Ready is never shown on presence alone. The page is read-only and loads only when opened or refreshed.',
  },
  {
    situation: 'What is the new Trusted Today page or Operator Home, where is /app/today, what needs me today for a community, or what does the new design preview show?',
    response: 'Today (address /app/today) is a preview of the new Trusted design for staff. Nothing links to it from the main app yet; open it by typing the address. Pick a community at the top. It shows a briefing of what needs you today, built only from three places: the Mail Queue (approved letters to print, and printed letters waiting to be confirmed mailed), Payables (bills waiting on your release, or on a manager review for staff), and the homeowner inbox (threads waiting on a staff reply in the last 7 days). Anything that is clear shows in the quiet "In good shape" strip. If one of those sources fails to load, the page says so instead of showing it as clear. The receivables card shows the owner aging total for the community and compares it with GL 1300 + 2400: it says it matches only when the difference is exactly $0.00, otherwise it shows the difference. Every item links to the screen in the main app where the work is done. The page is read-only and changes nothing. It loads only when opened or when you click Refresh.',
  },
  {
    situation: 'Who owned this property before, what was the prior owner or seller balance, did the seller close out at zero after the sale, which former owners still owe money or have a credit, or where is the ownership history for a house?',
    response: 'Two places, both read-only. (1) One property: Accounting → 👤 Homeowners → Accounts, search the owner, open the account and click 🏠 Ownership history. It lists the current owner and every prior owner with their ownership dates and a status: ✓ Closed cleanly, balance or credit remains, Activity after ownership ended (review), Unknown when there is no ledger data for that ownership period, or Ended before the conversion baseline (Unknown and before-baseline never mean $0). Balances only exist for communities whose owner ledger has been imported (a posted ledger conversion; today Lakes of Pine Forest only). For any other community the panel lists who owned the lot and when, and says the owner ledger history is not imported yet. Each owner has their own ledger with a running balance. For a sale it shows the balance at ownership end, the closing payoff (only when it is linked to the closed Home Sale and the seller\'s ownership period, never guessed from dates), and the final seller balance. Rows that cannot be tied to an owner are listed under Unassigned / needs review, and the lot total reconciles as the owners\' balances plus unassigned. (2) Every former owner: Accounting → 👤 Homeowners → Former Owners. It covers only communities whose owner ledger has been imported, lists which ones are not imported yet (never counted), and shows prior owners with a balance or with activity after ownership ended, and separately the legacy Vantaca accounts with no property or owner linked. Filters: all communities, debits or credits only, ownership ended date range, migrated/conversion only, and optional Unknown periods and $0 closes. It also shows an informational AR control against GL 1300 + 2400. Nothing on these screens changes a balance; write-offs, refunds or moves are separate approved actions. A journal entry tied to a homeowner charge or payment also shows the owner and ownership period and a 🏠 View owner ledger button.',
  },
  {
    situation: 'How do I see which journal entries make up a trial balance line, drill into an account balance, check that an account ties, or see an account balance for a specific period?',
    response: 'Open Accounting → 📊 Financials → Trial Balance. Click any account row or its debit/credit amount (each row says "View detail ›") and a panel opens with the exact posted journal-entry lines behind that account and fund: date, entry reference (click it to open the entry), description, source, and a paperclip for the source document when one is attached, with debit, credit and a running balance. The top line shows opening balance + period debits − period credits = ending balance, says which way the account normally runs (debit or credit balance), and shows a ✓ when the detail ties exactly to the trial balance row. Voided entries appear with their reversal so both sides net out. To see balances at a past date, set As of above the table and click Apply: every posted entry on or before that date counts, for every account. "All history" clears the date. A period-only view (a start date) is not offered yet. Long accounts page 100 lines at a time. It is read-only; nothing in the books changes.',
  },
  {
    situation: 'How do I plan a budget month by month, make pool or utility costs seasonal, put a project in a specific month, spread a contract across the year, or see why an amount is budgeted in a particular month?',
    response: 'Open Accounting → 📈 Budget → Budget, then click 📅 Monthly plan on a saved budget. Lines are grouped by report category. Click a line to see its Jan–Dec months; the annual is always the sum of the 12 months. On a draft budget you can type months directly or pick a phasing method (Even monthly, Prior-year budget pattern, Prior-year actual pattern, Contract schedule, Percentage-weighted, or Project / components), Apply it, then Save line. Changing the annual on a seasonal line asks how: scale the pattern, spread evenly, put the difference in chosen months, or keep the months to edit. Components show what is behind a line (for example a recurring repair allowance plus a fence project in October); when a line has components they must explain 100% of it, and "Add remainder as Recurring / base" fills the gap. The Timing basis column says what the months can claim: Documented (from the source document\'s own schedule), Calculated (derived by rule; a contract spread across its dates is marked Assumed until someone confirms it), or Manual. Approved budgets are view-only and locked; reopening one takes the owner and a reason.',
  },
  {
    situation: 'How do I group the income statement or budget vs actual by category, where are report categories set up, why is an account showing as Unmapped, or how do I change which category a GL account shows under?',
    response: 'Report categories decide how each income and expense GL account is grouped on Budget vs Actual (Grouped view) and the printed Income Statement vs Budget. They are presentation only: GL account numbers, names and amounts never change. Set them up per community in Accounting → ⚙️ Setup → Report Categories. Any staffer can view them; only admins can change them (add, rename, reorder or deactivate categories, or assign or unmap accounts). Each account maps to one category (optionally a subcategory); pick it from the dropdown on the account row, or tick several accounts and use Bulk → Assign. An account with no category shows under Unmapped in its section and is still included in every total, so nothing disappears. Use the Unmapped filter to find them. Every change is logged with who made it. On Budget vs Actual, the Flat / Grouped toggle switches views; Flat is the original account-by-account list. Only Lakes of Pine Forest has categories so far; other communities keep the previous grouping until theirs are set up.',
  },
  {
    situation: 'How do I collect a vendor\'s banking / ACH details securely, where is the vendor ACH enrollment form, how do I send a vendor a secure link to set up electronic payments, or is it safe to take bank account information by email?',
    response: 'Never take a vendor\'s bank account or routing number by plain email. Emailed banking details are the #1 accounts-payable fraud vector (business email compromise, where a scammer swaps in their own account). Instead use the secure ACH enrollment tool at /admin/ach: enter the vendor name (and optionally the community and a contact email) and it generates a one-time secure link. Send that link to the vendor by copying it or by having Emma email it straight from her mailbox (emma@bedrocktx.com) with the "Email via Emma" button; they enter their bank details into an HTTPS form, never by email, e-sign the authorization (typed name plus a consent checkbox), and can attach a voided check and their W-9 (collected in the same secure step, so a 1099 vendor is never left without a W-9 on file). On submit, trustEd generates a signed ACH Authorization PDF and files it into the community\'s document library, and staff can download it (and any upload) from the admin console. The link is single-use and expires (default 14 days), and only a hashed form of it is stored, so the link cannot be reused or leaked from our database. On the admin console the request moves through sent, submitted, verified. IMPORTANT: submitting the form does NOT authorize payment. Before any ACH is set up, a person must VERIFY the details by calling the vendor back at a known number (from the contract, not from the email), then mark the request Verified with a note on how it was confirmed. The full account number is shown only to the owner via Reveal (and that reveal is logged); everyone else sees the last four digits. This lives in trustEd; it is not a third-party service.',
  },
  {
    situation: 'A vendor bill Emma could not file has no invoice date (or no amount). How do I load a bill stuck in AP exceptions with "no date read" or "no amount read"? The bill only shows a service date.',
    response: 'Open Accounts Payable (address /admin/ap). Bills Emma saved but could not place are in the Exceptions box at the top, each with its reason (no date read, no amount read, needs a community, needs a vendor). On a bill with no invoice date, the card has an Invoice date box. When the bill prints a service date, the box is filled in with it; check it against the bill (click view the bill) and change it if needed. A bill with no amount has an amount box: type the amount due. If you want the bill coded to a specific expense account, pick it in the optional account list (only this community’s accounts are listed). Pick the community (and the vendor if asked) and click Send to Payables. There is nothing to re-send or re-upload: the bill loads from the file Emma already saved, through the same duplicate checks as every other bill, and goes to approval like any other payable. The date must be a real date, no more than 30 days in the future; if anything is wrong, the reason shows in red on the card and nothing is loaded. Who entered the date or amount, and when, is recorded on the exception and in the payable’s notes. A typed amount that does not match the bill’s own lines loads as one line and is flagged for review. If the bill itself prints a date or total, it cannot be typed over on this card; correct it on the payable after it loads. The one exception is a bill marked "dates look wrong": Emma read its dates but they failed the date check (for example an invoice date about two years before the bill arrived, which usually means the bill prints a two-digit year like 08/14/26 and the year was picked up from a footer or form revision stamp; a due date before the invoice date; or a service period in a different year). Nothing on such a bill was changed. Its card shows the invoice date, due date and service dates exactly as read: open the bill, correct any that are wrong and click Send to Payables (the corrected dates are checked again), or, if the dates really are right (an old bill), tick "dates are right as shown". What was corrected or confirmed, and by whom, goes in the payable’s notes, and Emma’s original reading is kept on the record.',
  },
  {
    situation: 'Which vendors need a W-9, where is the W-9 compliance queue, how do I get a vendor\'s W-9 for 1099s, how do I send a vendor a secure W-9 link, or does a missing W-9 stop a payment?',
    response: 'A missing W-9 never stops or delays a payment in trustEd. It is flagged so it is not forgotten. The W-9 compliance queue is on the Accounts Payable tab (the 🧾 W-9 compliance panel near the top, across all communities). Each row is a VENDOR, because one W-9 covers that payee at every association; click it to see the associations beneath it with what was paid this year by 1099 category against the threshold, how they were paid (check, ACH, autopay) and any open bills flagged "W-9 needed". Each vendor shows the action needed: W-9 request needed; Government exemption needs verification (a MUD); Provide Bedrock W-9 (Bedrock is the payee, so we give our own W-9); W-9 candidate found: review (a W-9 may already be in an email attachment; open and check it, nothing is attached automatically); or Classification/document review needed (a W-9 arrived and a person must confirm its tax classification). Vendors already over the threshold are listed even with no open bill, because they need a W-9 before January. To request a W-9, use the secure link tool at /admin/ach, choose Collect: W-9 only and pick the vendor record, then copy the link or have Emma email it; the vendor uploads the W-9 over an encrypted one-time form, never by email. A W-9 submitted that way is filed to the vendor\'s record automatically as its current W-9 (any earlier W-9 is kept as history), and the vendor moves to "review". A person then confirms the classification on the vendor record (Vendors → the vendor → W-9 on file), and confirms any corporate or government exemption with its basis (that is recorded and audited). The vendor drops off the queue on its own once the W-9 and classification, or a verified exemption, are stored. Names like Inc. or LLC are clues only and never clear a vendor. Books kept outside trustEd and demo communities are not counted.',
  },
  {
    situation: 'What is Virtual Claire, how does a homeowner talk to Claire on video, where is the Ask Claire tile, or can Claire waive a fine or approve an ARC request?',
    response: 'Virtual Claire is Bedrock\'s AI assistant with a face — a live video conversation, closer to a telehealth visit than a chatbot. It is one Claire behind three doors, and which door you came in decides what she can see: a homeowner gets their own account and their own community, a board member gets the communities they hold a seat on, staff get the portfolio. Homeowners start one from the "Ask Claire" tile on their portal home, or by going straight to /claire. Board members and staff use the same /claire page and pick the community first if they hold more than one. Everyone has to be signed in — Claire is never anonymous, because she answers questions about a specific account. In the visit you can talk (tap the microphone, best in Chrome or Edge) or type, captions run under the video, there is a Transcript button to see everything that was said, and "Talk to a person" hands off at any point with the whole conversation attached so nobody has to repeat themselves. Visits are capped, ten minutes for homeowners and thirty for board and staff, and every visit is saved to the association\'s records. WHAT SHE WILL NOT DO, and this is enforced in code rather than left to her judgment: Claire never waives, reverses or writes off a charge, never approves or denies an ARC/ACC request, never gives a legal opinion or says whether something is enforceable, never takes a payment or adjusts a balance, and never opens enforcement against a neighbor. Ask her any of those and she explains the rule, tells you where things actually stand, and routes it to a person — the decision stays with the association. She always identifies herself as AI, in the opening line and on a badge that stays on screen the whole time. She also has a library of short pre-recorded explainer videos (English and Spanish). If the video presenter is switched off or will not connect, the visit keeps going on voice and text and says so on screen.',
  },
  {
    situation: 'How do I share my contact info, where is BD, how do I get a digital business card or a QR code for my contact details, or I am out of business cards?',
    response: 'BD (business development) lives under Bedrock Office → 🤝 BD in the top nav. It produces a digital business card for anyone on the Bedrock roster. The core idea: the QR code carries your contact details themselves, not a link to a web page, so the camera on their phone decodes it locally and offers to add you as a contact with no wifi, no signal, and nothing to load. That matters because the moment you need it most is standing in a conference hall on dead hotel wifi. From the BD tab, pick the person, then download the kit: the Scan image (a full-screen QR — save it to your phone Photos, that is the one you hold out for someone to scan), the Card image (the branded card with your details visible — text or email this one), a Print sheet (ten 3.5x2in cards on a letter page, for printing on cardstock), and the .vcf contact file itself. There is also a public card page at /card/<name> — for example /card/ed — which anyone can open with no login; it shows the card with a big Save to Contacts button and a full-screen present mode. On iPhone you can put the scan image one tap from your home screen: Shortcuts app, add "Set Brightness 100%" then "Quick Look" on the image, then Add to Home Screen; assign it to Back Tap under Accessibility → Touch to pull it up by double-tapping the back of the phone. Screen brightness is the single biggest factor in whether a scan is instant. To add a new person to BD, their details go in lib/bd/people.js — that file is the single source of truth for every card surface, so a phone number changed there updates the card page, the QR, and every downloadable asset at once.',
  },
  {
    situation: 'How do I stream a board meeting to homeowners, run a live meeting or webinar, or where is Chamber?',
    response: 'Chamber is Bedrock\'s live-meeting system — board meetings streamed to verified homeowners inside their own portal, not a Zoom link. Staff run it from the Chamber console at /admin/chamber (top nav: Meetings group → 🎥 Chamber). Create a meeting, type the agenda (one item per line), pick the mode — Broadcast (televised, one-way to many watchers), Meeting (two-way, like a virtual board work session or a vendor/proposal presentation), or Webinar — paste the stream or room URL (a Daily room, or a Mux/Cloudflare player), then Go Live. While live you can advance the current agenda item, toggle Executive Session (which cuts the stream and recording for closed-session matters under Texas §209.0051 and shows homeowners a closed-session card), and run the Homeowner Forum request-to-speak queue (allow a homeowner, give them the floor, mark them done). Homeowners watch at /portal-chamber.html — a LIVE banner appears on their portal home when a meeting starts, with the synced agenda, meeting documents, an "attending online" count, and a Request to speak button; only verified owners/members can watch (renters and the public cannot). After the meeting, the console\'s Attendance report shows which properties attended and for how long against the community roster — a member-verified attendance record a Zoom link can\'t produce. The video runs on a white-label host (Daily/Mux/Cloudflare); Bedrock owns the access control, the agenda, the attendance, and the record.',
  },
  {
    situation: 'How do I make an event flyer, or email a flyer to the community — where is the Flyer Studio?',
    response: 'Flyer Studio is at /admin/flyer-studio (linked from the top of the 🗓️ Bedrock Calendar tab). Pick a community, type the event details, and optionally click "Polish wording with AI" to get a headline, tagline, and blurb (AI writes only the wording — dates, times, and locations stay exactly as you type them, never invented). Pick a look (theme), then "Create flyer" to see a live preview. You can download it as a print-ready PDF or a PNG image. To send it, use the Email panel: write a short message that appears above the flyer, and Send. During go-live testing the ONLY audience enabled is "Staff only (test)" — owner/resident sends are turned off in code until Ed enables them. The email goes out with the flyer embedded as an image AND attached as a PDF.',
  },
  {
    situation: 'How do I make a community newsletter — where is the Newsletter Studio, and how do I generate, edit, and publish a newsletter?',
    response: 'Newsletter Studio is at /admin/newsletter-studio (also linked from the top of the 🗓️ Bedrock Calendar tab). Pick a community + month + format (Community Update = 2-3 pages, Community Magazine = longer, Announcement = one-pager) and click "Generate draft" — Trusted assembles a first draft from data already in the platform: this month\'s events from the calendar, the board roster, community + emergency contacts, resident-portal links, a cover photo from the community photo library, and an AI-drafted "Message from the Board" plus an "HOA Corner" educational article whose topic is suggested from the community\'s most common recent violation type. The AI only writes editorial prose and never invents a date, fee, name, or link; anything it isn\'t sure of is flagged "review". You edit each section card (title, body, reorder with ↑/↓, add or delete sections), preview the web and print layouts, download a print-ready PDF, and Publish. Publishing produces a resident web link you can copy, email, or post to the portal. Meetings and clubhouse reservations shown come from their own modules. It is staff-usable (not owner-only).',
  },
  {
    situation: 'Where is the Bedrock Calendar — where do I see board and annual meetings, clubhouse reservations, staff events, and vacation / sick / time off, and how do I add a staff event or PTO day?',
    response: 'The Bedrock Calendar is a top-nav tab (🗓️). It is one month view that pulls everything together: annual-meeting cycle dates, scheduled board meetings (from the Agenda module), clubhouse / amenity reservations (from the amenity module), and staff events + PTO (vacation, sick, holidays, reminders). Meetings and clubhouse reservations are read-only here — they are pulled live from their own modules, so add or change those there. To add a staff event or a time-off day, click "＋ Add event", pick a type (staff event / vacation / sick / holiday / reminder), give it a title, optionally pick the staff member and a community (blank = company-wide), set the start (and an end date for a multi-day span), and Save. Click a staff/PTO chip to remove it. Filter by community with the dropdown. Everything is color-coded with a legend.',
  },
  {
    situation: 'Where do I see vendor projects, repairs, capital work, board projects, or things waiting on approval — bids, contracts, work in progress, what needs approving or paying? Where is the Operations dashboard?',
    response: 'Operations is a top-nav tab (🛠️, admin-only) at /admin/operations. It tracks every community project through its lifecycle — Requested → Bid requested → Bid received → Board deciding → Approved → Contract signed → Work started → Work complete → Closed — with the days a project has sat in its current stage, so nothing stalls unnoticed. The "Needs action" view is the queue of projects waiting on someone: approve scope, board vote, sign contract, approve invoice, pay vendor, follow up with a vendor. Each card shows the community, vendor, category (irrigation/landscaping/pool/electrical/etc.), cost, target completion, and the next action + who owns it; a red left-border means it is stalled past its soft SLA. Click a project to see its full timeline and add updates, advance it to the next stage, or edit it. Filter by community, and use "+ New project" to add one. A project sitting in Board deciding is what should feed the board packet\'s items-to-vote-on; an approved project is what an incoming vendor invoice gets matched against.',
  },
  {
    situation: 'How do I get prior meeting minutes or an agenda into the platform, or into a board packet? Can I just email them to Paige?',
    response: 'Yes — email Paige at paige@bedrocktx.com like you would a person: attach the minutes or agenda as a PDF (or paste the full text into the email body) and say what it is and which community, e.g. "please add this to Lakes of Pine Forest minutes." Paige reads the file, files it into the platform as a DRAFT record — minutes go to the Minutes module, agendas to the Agenda module — and replies confirming what she filed. It is a real association record from then on: searchable, exportable on takeover, and it flows into the board packet\'s Prior Minutes / Agenda section automatically for this meeting and every future one. A person still opens the Minutes/Agenda module to review and finalize it (drafts are never auto-finalized). If a file is a Word doc or a scan Paige can\'t read, she\'ll ask you to resend it as a PDF. You can also do it by hand in the Board Packets screen by dropping the PDF on the Prior Minutes or Agenda section card — but emailing Paige is the easy path.',
  },
  {
    situation: 'Where is Homeowner 360, how do I look up a homeowner or pull up a single address to see its violations in detail, the inspection photos, the letters we sent, the balance, and the history?',
    response: 'Homeowner 360 is a tab in the TOP navigation bar (labeled 360 with a person icon), or go to /admin/homeowner. It is NOT inside a property record. Search by name, address, email, or phone and one screen shows: open violations (each with the specific detail of what was seen, a Photo link to the inspection photo, and a Letter link to the exact letter that was mailed for that violation), balance + recent payments, ARC, pool access, all correspondence and calls, an AI recap, and a box at the bottom to add notes or upload emails to the record.',
  },
  {
    situation: 'Where do I see emails coming into info@ or claire@, Claire’s drafted replies, and how do I pull new mail or send an email as Claire?',
    response: 'Communications is a top-nav tab (envelope icon) at /admin/communications. During beta it is owner-only (only Ed sees it; other staff see a "coming soon" screen). It shows every email to info@ and claire@, auto-classified and linked to the homeowner, with a Claire-drafted reply for each to review, edit, and Approve & send (or dismiss). "Pull inbox" pulls new mail on demand; "New email" composes a fresh email as Claire. Nothing sends without approval.',
  },
  {
    situation: 'How do I send an email as Claire or Emma, or have one of them write an email for me to review before it goes out?',
    response: 'Use the "AI Team Email" top-nav tab (envelope icon, admin-only). At the top pick who it sends as: Claire (front office, for homeowners and boards, from claire@bedrocktx.com) or Emma (accounts payable, for vendors, from emma@bedrocktx.com). Enter recipients (commas for multiple, plus Cc), then either type the message or use "Have Claire/Emma write it" — give the gist, the AI drafts it, you edit, then Send. It goes out with the Bedrock logo + that person’s honest-AI signature; Claire’s mail logs on the homeowner’s record when the address matches. (Inside Communications, replies auto-send in the right voice — Emma for vendor/AP threads, Claire otherwise.)',
  },
  {
    situation: 'How do I add or upload a payment plan, and where do I see everyone who is on a payment plan?',
    response: 'Payment Plans is a top-nav tab (card icon) at /admin/payment-plans (admin-only). Pick the association and drop the signed payment-plan agreement PDF (or a firm report listing several) — the AI reads the terms (total balance, installment amount, frequency, dates), matches each to a property and its current owner, and you review before anything files. On approve, each plan is filed and appears on that homeowner’s 360 (in a Payment plans card) with a link to the signed agreement. The roster on the same page lists everyone currently on a plan across the portfolio, filterable by association and status (active/completed/defaulted/cancelled); each row links to that homeowner’s 360. A property has one active plan at a time — re-uploading a corrected agreement updates it rather than making a duplicate.',
  },
  {
    situation: 'Where do I see how much we spend with each vendor by community, run the 1099 report, upload a W-9, or set whether a vendor is 1099-required?',
    response: 'The Vendors tab (building icon, under Operations) is the vendor master. To capture past spend, use the "Historical Invoices (record only)" box — drop invoices already paid, pick the community and the paid date (the paid date drives the 1099 year, cash basis), and it files the spend and adds new vendors automatically. That box is for record only: anything that still needs to be PAID goes to Emma (accounts payable), not here. Current spend flows in automatically from what Emma pays, so each vendor\'s annual total combines both. Open a vendor to see its Tax & 1099 panel: toggle "1099 required", and drag/drop the vendor\'s W-9 PDF — the system reads the tax classification + TIN, files the W-9, and sets the 1099 flag (you can override). The "📊 Spend & 1099 Report" button runs the report: total paid per vendor by community for a tax year, with a "1099 file" view that shows vendors at or above the year\'s threshold ($2,000 for services and attorney fees in 2026; $600 for attorney gross proceeds), per community (each association is its own filing EIN), flags any 1099 vendor missing a W-9, links each W-9, and exports to CSV.',
  },
  {
    situation: 'Where do I register pool fobs or key tags and extended-hours swim forms, and how do I see who has pool access and their tag numbers?',
    response: 'Pool Access is a top-nav tab (swimmer icon) at /admin/pool-access. Pick a pool community (Waterview, Eaglewood, Lakes of Pine Forest, or Canyon Gate), then drop a batch of fob-registration or extended-hours PDFs — the system reads each form, matches the homeowner, and you review before anything files. The roster lists everyone with access and their tag numbers, and it also appears on the homeowner’s 360. To CHANGE a tag number, click the tag in the roster and type the new one. Use that when a fob is lost or reissued: it keeps the signed form and the authorized people attached to the record, and it writes a note saying what the tag used to be and who changed it. Do not revoke and re-add a record just to correct a tag, because that detaches the signed form behind it.',
  },
  {
    situation: 'How do I do a field inspection, capture violation photos, and where do the violation letters get drafted and printed?',
    response: 'The Inspect tab (under Operations) is the field tool: drive a community, capture photos, and the AI flags likely violations. Back at the office the Drafts queue holds a draft letter for each — review it, use Fix to correct the category if the AI got it wrong, Regenerate, or Reject, then Lock + Print. Regenerate only re-renders the current data; to change the violation type you must use Fix.',
  },
  {
    situation: 'How do violation letters work — courtesy notices, certified 209, force-mow, and general cleanup self-help letters?',
    response: 'Letters draft automatically from a violation in the Drafts queue and escalate courtesy 1 → courtesy 2 → certified 209. The 10-day certified self-help letters (force-mow for lawns, and general cleanup/abatement for trash/debris) draft from an open violation using the self-help button, but only for communities configured with their Declaration self-help authority (Eaglewood is set up). Every letter is reviewed and Locked before printing. The exact letter that was mailed is linked on the homeowner’s 360.',
  },
  {
    situation: 'Where do I see violations coming due, cure deadlines, lapsed cures, and certified 209 cases across communities?',
    response: 'The Cures tab (sprout icon) is portfolio case management: what is coming due in the next 30 days, what has lapsed past its cure date, and the certified 209 cases per community. The cure-lapse processor advances expired violations to the next stage and drafts the new letter.',
  },
  {
    situation: 'What is askEd and how do I ask a question about a community, a homeowner’s account, Texas 209, or how to handle a situation?',
    response: 'askEd is the staff AI assistant (brain icon, top nav). Ask it about a community’s governing documents, Texas Property Code 209, a homeowner’s account, vendor contacts, or how to handle a situation — it answers grounded in the documents and account data. Quick mode is for fast facts; full mode gives advisor-level reasoning. It is Bedrock’s own tool, not a vendor — there is no external support desk.',
  },
  {
    situation: 'Where do I see what a homeowner owes, receivables, aging, or the general ledger?',
    response: 'A homeowner’s balance shows on their 360. Owner Receivables (Owner AR) ingests Vantaca AR aging PDFs into per-property balance snapshots. The general ledger / accounting lives at /admin/accounting (Finance). Vantaca is still the live ledger; trustEd mirrors it until the GL cutover for each community.',
  },
  {
    situation: 'How do I see a community map with each house and its violations, owner, and balance?',
    response: 'The Community Map shows every house in a community as a clickable tile. Click a house to see its open violations, ACC, AR, and owner — the same data as Homeowner 360, on the map. Field crews also use it to locate properties on a drive.',
  },
  {
    situation: 'Where do I see the team’s work, what is due, and what might fall through the cracks?',
    response: 'The Status tab (clipboard icon) is the team work board: every inbound mail and email plus every active project, each with an owner, a status, and an SLA due date from the Operations Standard, so nothing falls through.',
  },
  {
    situation: 'How do I search a community’s governing documents, CC&Rs, or bylaws?',
    response: 'The Documents tab keyword-searches a community’s uploaded governing documents. For a reasoned answer that combines the documents with Texas 209 and the homeowner’s account, ask askEd instead.',
  },
  {
    situation: 'How do I handle a resale request, a closing, or a new-owner ownership transfer?',
    response: 'Home Sales (/admin/home-sales) handles resale requests before closing and closing packets after: scan the title company’s closing mail and the system records the ownership transfer from seller to buyer and the transfer fee. The seller named on the closing document must match the owner on file, so a lot sold twice (even on the same day) is entered one closing at a time, in order. Clicking a red DRV badge such as "1 open" shows that home’s violations read-only (category, opened date, status, most recent notice, next step), with a link to the full record in Homeowner 360.',
  },
  {
    situation: 'When Lennar sells a Still Creek Ranch lot to its first homeowner, how is the year’s assessment split? Where do I see the builder and homeowner proration?',
    response: 'It happens inside the closing itself. When you Record closing in Home Sales (or Approve in Ownership Review) for a Still Creek Ranch lot whose seller is Lennar, trustEd shows the assessment proration before anything is written: the annual assessment, Lennar’s 50% builder rate, the transfer date, Lennar’s days (Jan 1 through the day before the transfer) and the new owner’s days (transfer date through Dec 31), and both prorated amounts. You confirm it, then the transfer and the proration post together: Lennar’s account gets a charge or credit so it ends with only its 50%-rate share for the year, and the new owner is charged their full-rate share. Both lines tie to the transfer and post on Still Creek’s own revenue treatment: the new owner’s share goes to 2205 Unearned Income and is released to 4000 by a recognition schedule month by month for the days it covers in each month (the closing month only its own days, released on the closing date; every later month on its 1st), Lennar’s share (already elapsed) goes to 4000, but only once the community’s accounting conversion is posted. Until then the closing still shows and saves the calculation (the proration is staged with the transfer) and nothing is charged, credited or posted, because the year’s billing is not yet in trustEd’s books; Every proration not yet posted is listed under Builder transfer prorations at the top of Home Sales as Staged (waiting for the conversion), Ready to Post (recomputed; Review & post shows the numbers and posts only when you confirm) or Blocked (with the reason, e.g. an unclear builder charge, or a builder annual assessment already billed and deferred, which waits until the community’s accounting conversion normalizes it to the builder rate; the closing never changes community-wide revenue schedules). If Lennar’s existing assessment activity for the year is unclear, trustEd lists it and does not guess: you can record the ownership change and post the proration from the sale once the ledger is clear. The rates live in the community’s assessment rates (the builder rate is a percent of the homeowner rate), so an assessment change flows through. Other communities and homeowner-to-homeowner sales are unchanged.',
  },
  {
    situation: 'How do I log physical mail that comes into the office?',
    response: 'Mail Scan (mailbox icon) is physical-mail intake: scan a piece of mail and the system classifies it, routes it, and logs it to the association record.',
  },
  {
    situation: 'Where do I get an NDA to have a bank, insurance company, media company, or partner sign before we share our platform internals? Where are our legal documents / disclosures?',
    response: 'Legal Disclosures lives under Bedrock Office (the /legal-disclosures page) — it holds Bedrock’s own versioned legal documents (privacy policy, disclosures, and agreements), editable by an admin. The Mutual Non-Disclosure Agreement is there as a document titled "Mutual Non-Disclosure Agreement" (an "agreement" category doc). It’s a mutual NDA under Texas law (venue Fort Bend County) written to protect Bedrock’s trustEd platform internals — broad confidential-information definition, a no-reverse-engineering / no-benchmarking clause, no license or IP transfer, and standard term/return/injunctive-relief clauses. To have someone sign it: open the NDA in Legal Disclosures and use the "Prepare a copy to sign" panel — enter the counterparty’s legal name, the effective date, and the Bedrock signatory — and it generates a Bedrock-branded PDF with signature blocks for both parties to send out for signature. Preparing a copy never changes the master; an admin can edit the master text (which bumps its version) and the generated copies use the current text. Note it should be reviewed by counsel before first use.',
  },
  {
    situation: 'How does the board vote on a motion or approval, and where do we see who voted and whether it passed?',
    response: 'The board portal has a Motions & Voting tile (under Governance). Any board member (or a manager on their behalf) records a motion — for example “Approve the Versatex sidewalk estimate.” Each active board member casts For, Against, or Abstain with an optional comment. The motion shows a live tally, quorum, and the result, plus exactly who voted which way. It auto-finalizes once every seat has voted, or a chair/manager can close it early. This is the board’s internal approval record and belongs in the minutes — it is separate from community-wide homeowner elections.',
  },
  {
    situation: 'How do I generate an insurance RFP to shop a community’s insurance renewal, get quotes from brokers, or send agents what coverage we need? Where is the insurance program? Can I email Amanda to prepare an insurance RFP?',
    response: 'The insurance RFP is its own capability, separate from a normal vendor/landscaping RFP — an insurance renewal is a spec of coverage, not a scope of labor. It works in two steps. FIRST the current program becomes a record: upload every in-force policy declarations PDF for the community (GL, Property, D&O, Umbrella, Crime, Cyber, Workers Comp — one per line, the whole binder, not just the casualty policies) to the insurance program screen. Trusted reads each dec, pulls the coverage line, limits, deductibles, and key terms, and files it as the community’s insurance program of record. SECOND, generate the RFP: it renders a clean, Bedrock-branded Request for Proposal that tells brokers the COVERAGE SCOPE the association needs quoted — each line with its limits, deductibles, and the key terms to match — and deliberately WITHHOLDS the incumbent carrier and the expiring premium, so competing agents quote fresh against the requirement instead of just undercutting whoever writes it now. There is a completeness guard: if the program is missing a line that the association actually carries (for example the Property or Cyber policy wasn’t uploaded, or Crime came through with no limits), the system REFUSES to generate the RFP and names the missing line, rather than quietly send a broker half the program. So if the RFP is blocked, the fix is to upload the missing policy PDF and re-file the program. YOU CAN ALSO JUST ASK AMANDA: email amanda@bedrocktx.com — "please prepare the insurance RFP for [community]" — and she generates it from that community’s policy of record and emails the finished RFP PDF back to whoever asked. If the program is incomplete she doesn’t send half of it; she replies naming the missing policy so it can be uploaded first. The whole point is that every broker gets the same uniform spec and quotes apples-to-apples, and the association’s actual policy forms are never exposed to a competitor.',
  },
  {
    situation: 'How do I change an AI teammate’s voice, or the voice/accent of the live video avatar (Claire, Tessa, or anyone on the AI team)? A teammate has the wrong accent.',
    response: 'AI-team voices are set from the Voices picker at /admin/voices (owner-only; linked from the AI Team Scorecard). Each teammate is listed with their current voice and a play button to hear it; click "Change voice" to audition the available voices (press play on any of them) and "Use" to set one. Only voices that the live (interactive) video avatar can actually speak are shown, in English and Spanish. A choice takes effect immediately for the live avatar and any rendered video — no redeploy — because it is saved per teammate and overrides the environment default. This is the fix when a teammate has the wrong accent (for example a British-reading voice on someone who should sound American): open Voices, audition, and Use the right one.',
  },
  {
    situation: 'Where is the canonical identity of each AI teammate kept (their face, voice, wardrobe, persona)? How do I see which version of Amanda made a video, approve a new face, or roll a character back?',
    response: 'The Character Canon page at /admin/characters (owner-only; also a tile on Systems Admin) is the registry of who each AI teammate is. Each character has a permanent ID and independently versioned components: face, body, voice, wardrobe, persona and guardrails. A release bundles one approved version of each; the current release is who the character is today, and older releases stay preserved as legacy. Proposed changes show an Approve button that says exactly what will be approved. To roll back, use Make current on an earlier release; nothing is ever deleted. Canonical images are stored privately by content hash and the Verify button re-checks every file. Provider IDs (HeyGen avatars, ElevenLabs voices) are listed as mappings, and the Production vs canon table shows where the live app still uses an older version. Production rendering does not read this registry yet.',
  },
  {
    situation: 'Where do I see everything that needs a person across the AI team (bills to review, ACC decisions waiting, board packets due, stuck intake), and what Amanda would do?',
    response: 'Open the new Today home at /app/today (admin). The Amanda · Operations card at the top of the lower section lists what needs a person, oldest and most urgent first, each with the teammate it belongs to (Emma for payables, Annie for ACC, Paige for board packets, Amanda for anything cross-cutting): bills flagged for review or held as possible duplicates, emailed bills Emma could not load, ACC decisions drafted and waiting for a reviewer, board packets still in draft within a week of the meeting, and failed scheduled jobs. A one-line summary at the top says how many items need a person and what was handled in the last 24 hours. Click any item to open its history (who did what, when) and a button to the screen where you act on it. The card is read-only: approvals and other actions stay on their own screens, where their usual checks apply. Switch between All communities and This community at the top right. If a source does not answer, the card says so instead of showing zero.',
  },
  {
    situation: 'How do we bring a new community in from another management system (Vantaca, CINC, spreadsheets)? Where is the conversion / onboarding batch, what stage is it in, and who can waive a failed control or move it forward?',
    response: 'Use the Onboarding Engine at /admin/onboarding (a tile on Systems Admin). Under Start onboarding, pick the community, the legacy system and the cutoff date: Trusted then lists exactly which reports to download, by the name the legacy system prints on them and dated for that cutoff (for Vantaca: GL Trial Balance, Balance Sheet, AR Aging, Homeowner Transaction History, Pre Paid Homeowners including previous owners, and AP Aging), with the file name Vantaca usually saves each under. Choose the PDFs as exported and the list marks each one Supplied, Needed or Wrong date before you start; no spreadsheet editing is needed. Click Start onboarding and the operator does the rest: it recognizes each report, checks it against its own printed totals, asks by name and date for anything missing or misdated, and continues on its own when you upload it. It stops only for a genuine exception, a judgment call, or the owner authorization. Only the owner can waive a failed control (with a written reason; it stays shown as FAIL, waived) or advance past one. The batch page shows the operator panel first, then your decisions; manual stage controls sit under Advanced for admin recovery only. Nothing in this tool writes to a community’s books; the execute step is not built yet.',
  },
];

(async () => {
  // Idempotent: clear the prior platform-knowledge set (both category labels
  // used during rollout) so this file stays the single source of truth.
  const { error: delErr } = await sb.from('playbook').delete().in('category', ['platform_feature', 'platform_navigation']);
  if (delErr) console.warn('delete prior entries:', delErr.message);

  let inserted = 0;
  for (const f of FEATURES) {
    let embedding = null;
    try {
      const emb = await openai.embeddings.create({ model: 'text-embedding-ada-002', input: f.situation.replace(/\s+/g, ' ').slice(0, 8000) });
      embedding = emb.data[0].embedding;
    } catch (e) { console.warn('embed failed (saving without):', e.message); }
    const { error } = await sb.from('playbook').insert({
      situation: f.situation, response: f.response,
      category: 'platform_feature', tags: ['navigation', 'how_to', 'platform'],
      applies_to: ['asked'], reasoning: 'Platform self-knowledge so askEd/Claire answer how-to questions correctly instead of hallucinating.',
      embedding,
    });
    if (error) { console.warn('insert failed:', error.message); continue; }
    inserted += 1;
  }
  console.log(`platform knowledge seeded: ${inserted}/${FEATURES.length} entries`);
})().catch((e) => { console.error('ERR', e.stack || e.message); process.exit(1); });
